Canner/wren-engine

- .github/workflows/build.yml
- .github/workflows/integration-tests.yml
- .github/workflows/test-with-secrets.yml
follow https://github.com/imjohnbo/ok-to-test
As someone with write access, comment /test-with-secrets sha=<head-sha> on an incoming pull request. The head sha is the first seven characters of the most recent commit of the incoming pull request.
Here is the recommended flow:
- A fork pull request is opened.
- A unit test workflow runs. Secrets are not available to this workflow.
- Someone with [write access](https://help.github.com/en/github/getting-started-with-github/access-permissions-on-github) looks over the pull request code. ⚠️ Before proceeding, they should be sure the code isn't doing anything malicious like secret logging. ⚠️
- They comment /test-with-secrets sha=<head-sha> on the pull request.
- A repository_dispatch API request is sent to this repository. 
- An integration …
> Add test with secrets when using pr in forked projects

- accio-base/src/main/java/io/accio/base/type/TimestampType.java
- accio-connector-client/src/main/java/io/accio/connector/postgres/PostgresRecordIterator.java
- accio-main/src/main/java/io/accio/main/connector/bigquery/BigQueryRecordIterator.java
- accio-main/src/main/java/io/accio/main/connector/postgres/PostgresSqlConverter.java
- accio-main/src/main/java/io/accio/main/sql/postgres/RewriteToPostgresType.java
- accio-pre-aggregation/src/main/java/io/accio/preaggregation/DuckdbRecordIterator.java
- accio-tests/src/main/java/io/accio/testing/DataType.java
- accio-tests/src/test/java/io/accio/testing/AbstractWireProtocolTypeTest.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolTypeWithBigQuery.java
- accio-tests/src/test/java/io/accio/testing/postgres/AbstractWireProtocolTestWithPostgres.java
- accio-tests/src/test/java/io/accio/testing/postgres/TestWireProtocolTypeWithPostgres.java
- trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
The mainly is to add PostgreSQL datasource type test, but also fix the following things to make type test working.
What we do,
1. Remove `tinyint` type test, because there is no `tinyint` type in PostgreSQL
2. Fix PostgreSQL connector type
- `bytea` type
- `timestamp` type
- `varchar` type with `unicode`
We can improve the type test by modify expected result. https://github.com/Canner/accio/issues/363
> Add and Fix PostgreSQL datasource type test

- accio-base/src/main/java/io/accio/base/dto/Model.java
- accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/ModelInfo.java
- accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestModelSqlRewrite.java
Support model based on model
baseModel field is added in this pr
```json
{
"name":"BookReplica",
"refSql":null,
"baseModel":"Book",
"columns":[
{
"name":"authorId",
"type":"STRING",
"relationship":{
"empty":true,
"present":false
}
}
]
}
```
> Support model on model

- accio-base/src/main/java/io/accio/base/CatalogSchemaTableName.java
- accio-cache/src/main/java/io/accio/cache/CacheManager.java
- accio-cache/src/main/java/io/accio/cache/TaskInfo.java
- accio-main/src/main/java/io/accio/main/AccioManager.java
- accio-main/src/main/java/io/accio/main/web/CacheResource.java
- accio-tests/src/test/java/io/accio/testing/RequireAccioServer.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestRefreshCache.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestReloadCache.java
- accio-tests/src/test/resources/cache/cache_frequently_mdl.json
- generate cache data on a per-table basis
- create the caching task for each dataset(model & metric)
> Generate cache data on a per-table basis

- accio-shaded/pom.xml
Since trino 375 use a very old version of jgraph (0.9.0) which is far away of what the version in accio (1.5.2). Upgrade jgrapht in trino 375 takes lots of effort. Here we add jgrapht to shaded jar.
> Add jgrapht to shaded

- accio-base/src/main/java/io/accio/base/jinjava/JinjavaExpressionProcessor.java
- accio-base/src/test/java/io/accio/base/dto/macro/TestMacro.java
- accio-base/src/test/java/io/accio/base/jinjava/TestJinjavaExpressionProcessor.java
Support the macro definition like:
```
"name": "resolution_time",
"definition": "() => closed_date - created_date"
```
> Fix Define Macro without any parameters

- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
We followed the [Trino function standard](https://trino.io/docs/current/functions/aggregate.html). Then, we should handle the different behavior for each source type.
In this PR, we handle `count_if` and `array_agg` function for bigquery.
- count_if: The function name should be `countif`.
- array_agg: BigQuery doesn't allow null elements in an array. We should add `ignore nulls` for every `array_agg` calling.
> Support count_if and array_agg function for BigQuery data source

- accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/MetricSqlRender.java
- accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestMetric.java
- accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestMetricViewSqlRewrite.java
For example, rewrite `count(orderkey)` to `count(Orders.orderkey)`.
> Add model prefix for identifiers used in measure expression

- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
We followed [the spec of Trino's date_diff function](https://trino.io/docs/current/functions/datetime.html). Rewrite this function to `Timestamp_diff` in BigQuery.
> Support date_diff function for BigQuery Dialect

- accio-cache/src/main/java/io/accio/cache/CacheManager.java
- accio-cache/src/main/java/io/accio/cache/CacheModule.java
- accio-cache/src/main/java/io/accio/cache/EventLogger.java
- accio-cache/src/main/java/io/accio/cache/Log4jEventLogger.java
- accio-cache/src/main/java/io/accio/cache/TaskInfo.java
Now we have an interface for logging the cache event. There're 2 kind of events will be logged: 
- Create Cache : It include creating a new cache and refreshing a old cache.
- Remove Cache: When remove a cache successfully, it logs this event.
We only provide one implementation for `EventLogger`.
- Log4jEventLogger: Its behavior is depending on how user setup his log4j.properties
> Add Event Logger for Cache Event

- accio-base/src/main/java/io/accio/base/type/TimestampWithTimeZoneType.java
- accio-base/src/test/java/io/accio/base/type/TestTimestampWithTimeZoneTypeParsing.java
- accio-connector-client/src/main/java/io/accio/connector/bigquery/BigQueryType.java
- accio-main/src/main/java/io/accio/main/pgcatalog/builder/BigQueryUtils.java
- accio-main/src/test/java/io/accio/main/pgcatalog/builder/TestCreateBigQueryTempTable.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- Remove relationship field from pg_catalog:
A relationship field in a model shold be used in runtime. We can't put them to the pg_catalog.
- Support TIMESTAMP_WITH_TIMEZONE
There're many time-related filter operation in Metabase. We only support time-specified(ex. range or specified day) operation now.
> Fix PGwire-related issues for Metabase

- accio-base/pom.xml
- accio-base/src/main/java/io/accio/base/client/duckdb/DuckDBConfig.java
- accio-base/src/main/java/io/accio/base/client/duckdb/DuckdbClient.java
- accio-cache/src/main/java/io/accio/cache/CacheManager.java
- accio-cache/src/main/java/io/accio/cache/CacheModule.java
- accio-main/src/main/java/io/accio/main/web/CacheResource.java
- accio-testing/src/main/java/io/accio/testing/AbstractTestFramework.java
- accio-validation/src/test/java/io/accio/TestMetricValidation.java
There're 3 configurations exposed by this PR:
- `duckdb.memory-limit`: To set `memory_limit` in DuckDB. The default value is `the runtime max heap size / 2`
- `duckdb.home-directory`: To set `home-directory` in DuckDB.
- This config is disable because the known issue: https://github.com/duckdb/duckdb/issues/10062
-  `duckdb.temp-directory`: To set `temp-driectory` in DuckDB.
> Add DuckDBConfig to handle the system resource configurations

- accio-cache/src/main/java/io/accio/cache/DefaultCachedTableMapping.java
We may occur null exception if the specific table isn't exist in table mapping. Add an Optional to avoid the null exception.
> Avoid to get the null exception when cache rewriting

- accio-base/src/main/java/io/accio/base/AccioMDL.java
- accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/AccioDataLineage.java
- accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/AccioSqlRewrite.java
- accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestAccioDataLineage.java
- accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestModel.java
- calculated fields that use relationship should also have joinkeys in required fields.
- remove field itself from required fields
- fix calculated field can't use non-calculated column in same model
- fix model on model lineage
> Fix error with dynamic calculated expression with non-calculated field in same model

- accio-base/src/main/java/io/accio/base/type/BaseTimestampType.java
- accio-base/src/main/java/io/accio/base/type/DateType.java
- accio-base/src/main/java/io/accio/base/type/NumericType.java
- accio-base/src/main/java/io/accio/base/type/TimestampType.java
- accio-base/src/main/java/io/accio/base/type/TimestampWithTimeZoneType.java
- accio-connector-client/src/main/java/io/accio/connector/bigquery/BigQueryType.java
- accio-tests/src/main/java/io/accio/testing/TestingWireProtocolClient.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- Support more type parameter passed by native protocol.
- `numeric`, `date`, `timestamp`, `timestamptz`, `bytea`, `interval`, `array`.
> Fix prepared statement parameter for BIgQuery

- accio-main/src/main/java/io/accio/main/web/LineageResource.java
- accio-main/src/main/java/io/accio/main/web/dto/ColumnLineageInputDto.java
- accio-main/src/main/java/io/accio/main/web/dto/LineageResult.java
- accio-main/src/main/java/io/accio/main/web/dto/SqlLineageInputDto.java
- accio-server/src/main/java/io/accio/server/module/WebModule.java
- accio-tests/src/test/java/io/accio/testing/RequireAccioServer.java
- accio-tests/src/test/java/io/accio/testing/TestLineageResource.java
follow up #421 
This PR implement the APIs for lineage analysis. Now, we has one for MDL column lineage. We will present another to analyze the column lineage used by a SQL soon.
Analyze a lineage for a column expression. User can append a manifest runtime or use the deployed manifest in default.
```
GET /v1/lineage/column
```
```
{
"manifest": { ... },
"datasetName": "Customer",
"columnName": "revenue"
}
```
```
[
{
"name": "Orders"
},
{
"name": "Lineitem",
"columns": [
{
"name": "extendedprice",
"properties": { "type": "REAL" }
},
{
"name": "discount",
"properties": { "type": "REAL" }
},
]
}
]
```
> Implement Lineage Analysis API

- accio-main/src/main/java/io/accio/main/AccioManager.java
- accio-main/src/main/java/io/accio/main/pgcatalog/function/PgFunctions.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolTypeWithBigQuery.java
Currently TestBigQueryType.testInterval and TestWireProtocolTypeWithBigQuery>AbstractWireProtocolTypeTest.testInterval always fail. When the sql result contains PGInterval type, pg jdbc driver 42.3.1 will send a SQL as follows ([code reference](https://github.com/pgjdbc/pgjdbc/blob/3cf846e019767590cc1a4c1b90246ebc26bc5130/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L539-L550))
```sql
SELECT n.nspname = ANY(current_schemas(true)), n.nspname, t.typname 
FROM pg_catalog.pg_type t
JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = ?
```
and currently pg_type table always use `pg_catalog` to generate oid in column typnamespace while function current_schemas won't have any schema that named `pg_catalog` since every test suite use a random pgcatalog name.
We …
> Fix interval type test

- accio-main/src/main/java/io/accio/main/PostgresNettyProvider.java
- accio-main/src/main/java/io/accio/main/PostgresWireProtocolConfig.java
- accio-main/src/main/java/io/accio/main/wireprotocol/PostgresNetty.java
- accio-main/src/main/java/io/accio/main/wireprotocol/PostgresWireProtocol.java
- accio-main/src/main/java/io/accio/main/wireprotocol/WireProtocolSession.java
- accio-main/src/main/java/io/accio/main/wireprotocol/auth/Authentication.java
- accio-main/src/main/java/io/accio/main/wireprotocol/auth/FileAuthentication.java
- accio-server/src/main/java/io/accio/server/module/PostgresWireProtocolModule.java
- accio-tests/pom.xml
- accio-tests/src/main/java/io/accio/testing/TestingWireProtocolClient.java
- accio-tests/src/test/java/io/accio/testing/AbstractWireProtocolTest.java
- accio-tests/src/test/java/io/accio/testing/bigquery/AbstractWireProtocolTestWithBigQuery.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- accio-tests/src/test/resources/accounts
Support to import an account file to do create some accounts in Accio.
`pg-wire-protocol.auth.file` is the path to the account file.
The file format is `userName password`. Ex.
```
pekochan pekopeko
ina wah
gura a
```
If accounts file isn't exist or is empty, the authentication is disable.
> Simple File-based Authentication

- accio-cache/src/main/java/io/accio/cache/CacheManager.java
- accio-cache/src/main/java/io/accio/cache/DuckdbTaskManager.java
- accio-main/src/main/java/io/accio/main/wireprotocol/PostgresNetty.java
This won't happen in production since the only way to close accio server means kill process. 
While some executor is not shutdown and cause thread leak in e2e tests.
> Shutdown all executors to avoid thread leak

- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Analysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/ExpressionAnalysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/matcher/Matcher.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/matcher/PredicateMatcher.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestStatementAnalyzer.java
- accio-main/src/main/java/io/accio/main/web/AnalysisResource.java
- accio-main/src/main/java/io/accio/main/web/LineageResource.java
- accio-main/src/main/java/io/accio/main/web/dto/PredicateDto.java
- accio-main/src/main/java/io/accio/main/web/dto/SqlAnalysisInputDto.java
- accio-main/src/main/java/io/accio/main/web/dto/SqlAnalysisOutputDto.java
- accio-server/src/main/java/io/accio/server/module/WebModule.java
- accio-tests/src/test/java/io/accio/testing/RequireAccioServer.java
- accio-tests/src/test/java/io/accio/testing/TestAnalysisResource.java
- accio-tests/src/test/java/io/accio/testing/TestMDLResource.java
Add new web api /v1/analysis/api, this api will retrieve predicates in where-clause. Note that this api only catch predicate format in `[Identifer/dereferenceExpression] [operator] [literal/identifier/dereferenceExpression]`. e.g. `column = 'foo'` will be caught while `column_a = column_b` won't be caught since column_b is an identifier not literal.
manifest is optional, if manifest is not provided in input dto, mdl provided in accio server will be used.
```json
{
"manifest":  {...},
"sql": "SELECT * FROM Orders WHERE orderdate >= DATE '2022/07/12' AND orderkey <= 123 OR orderkey >= 100"
}
```
```json
[
{
"modelName": "Orders",
"columnName": "orderdate",
"predicates": [
{
"operator": ">=",
"value": "DATE '2022/07/12'"
}
]
},
{
"modelName": "Orders",
"columnName": "orderkey"
"predicates": …
```
> Add analysis sql web api

- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/BaseRewriter.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/BaseTreeRewriter.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/MetricRollupRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/Utils.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/ViewInfo.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Analysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/ExpressionTypeAnalyzer.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Scope.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/TypeCoercion.java
- accio-base/src/main/java/io/accio/base/type/PGTypes.java
- accio-base/src/main/java/io/accio/base/type/TimestampType.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestExpressionTypeAnalyzer.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestStatementAnalyzer.java
- accio-main/src/main/java/io/accio/main/connector/bigquery/BigQuerySqlConverter.java
- accio-main/src/main/java/io/accio/main/sql/bigquery/TypeCoercionRewrite.java
- accio-main/src/main/java/io/accio/main/sql/bigquery/analyzer/BigQueryTypeCoercion.java
- accio-main/src/main/java/io/accio/main/web/AnalysisResource.java
- accio-tests/src/test/java/io/accio/TestBigQuerySqlConverter.java
- accio-tests/src/test/java/io/accio/testing/bigquery/AbstractWireProtocolTestWithBigQuery.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestBigQueryCache.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestFunctions.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- accio-tests/src/test/resources/tpch_mdl.json
- trino-parser/src/main/java/io/trino/sql/util/IntervalLiteralUtil.java
Refer to [BigQuery Type Conversion Rule](https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_rules), it's very weak to do timestamp-related type conversion. If the timestamp-related type can't be work with other time type, such as `DATE`, `TIME`, it's very inconvenience for normal SQL user.
In this PR, we supports to detect the Type Coercion request automatically. Any type coercion request, we may wrap what need to be coerced in a `CAST` expression. For now, any type coercion is based on what type left side is.
Now, user can query like as below, assume `shipdate` is a `TIMESTAMP` column in BigQuery.
```
SELECT shipdate FROM Lineitem WHERE shipdate > current_date + interval '1' day
```
- Function list for return type.
- Handle remote function name.
- Handle timestamp …
> Implement basic Type Coercion for BigQuery connector

- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioDataLineage.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/DummyInfo.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestCumulativeMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModel.java
Some BI tools will select a table without any required field like `Metabase` query a table using:
```sql
SELECT true "_"
FROM
Metric_Revenue
WHERE (1 <> 1)
LIMIT 0
```
We should create a dummy CTE when required fields is empty but exist selected tables.
> Create dummy CTE when selecting table without any required field in dynamic mode

- .github/workflows/build-image.yml
The new workflow can receive a specific branch to build the image. It also can receive a specific docker image tag name instead of the default name `branchName-commitSHA`.
> Add CI to build image with specify branch and commit

- accio-base/src/main/java/io/accio/base/AccioMDL.java
- accio-base/src/main/java/io/accio/base/dto/Column.java
- accio-base/src/main/java/io/accio/base/dto/Relationship.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioDataLineage.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/MetricSqlRender.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/ModelSqlRender.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/Utils.java
- accio-base/src/test/java/io/accio/base/dto/TestRelationship.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetricViewSqlRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModelSqlRewrite.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestDuckdbRetryCacheTask.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestDuckdbTaskManager.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
- accio-tests/src/test/resources/bigquery/TestWireProtocolWithBigquery.json
Add quote for all column name or table name identifier to support reserved SQL reserved word as name.
- The test in 17595f9 will be failed in CI but work in the local.
> Add quote for all identifier to support SQL reserved word as name

- accio-base/src/main/java/io/accio/base/AnalyzedMDL.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestAllRulesRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestCumulativeMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestEnumRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetricViewSqlRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModel.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModelSqlRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestView.java
- accio-main/src/main/java/io/accio/main/AccioManager.java
- accio-main/src/main/java/io/accio/main/AccioMetastore.java
- accio-main/src/main/java/io/accio/main/PreviewService.java
- accio-main/src/main/java/io/accio/main/web/MDLResource.java
- accio-main/src/main/java/io/accio/main/web/dto/CheckOutputDto.java
- accio-main/src/main/java/io/accio/main/web/dto/DeployInputDto.java
- accio-tests/src/test/java/io/accio/TestBigQuerySqlConverter.java
- accio-tests/src/test/java/io/accio/testing/RequireAccioServer.java
- accio-tests/src/test/java/io/accio/testing/TestMDLResource.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestDuckdbRetryCacheTask.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestDuckdbTaskManager.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestRefreshCache.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestReloadCache.java
Add `version` field to assign the version of MDL.
```
POST /v1/mdl/deploy
```
```json
{
"manifest": {
"models": [
{
"refSql": "...",
"columns": [ ... ],
"properties": {}
},
{
"name": "Lineitem",
"refSql": "...",
"columns": [ ... ]
},
{
"name": "Customer",
"refSql": "...",
"columns": [ ... ]
}
],
"relationships": [
...
]
},
"version": "xxxx"
}
```
Now, only return the version instead of full manfiest.
```
GET /v1/mdl/status
```
```json
{
"systemStatus": "READY",  // READY, PREPARE 
"version": "xxx"
}
```
Now, `manifest` is optional. Use deployed MDL when previewing if the manifest isn't carried.
```
GET /v1/mdl/preview
```
Return the current deployed MDL.
```
GET /v1/mdl
```
```json
{
"models": [
{
"refSql": "...",
"columns": [ ... ],
"properties": {}
}, …
```
> Modified MDL-related API

- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModel.java
After #451, we will create dummy CTE for required table but we should exclude the table which doesn't exist actually.
> Throw error if a specific table isn't found

- accio-main/src/main/java/io/accio/main/wireprotocol/PostgresWireProtocol.java
- accio-main/src/main/java/io/accio/main/wireprotocol/WireProtocolSession.java
- accio-main/src/main/java/io/accio/main/wireprotocol/auth/Authentication.java
- accio-main/src/main/java/io/accio/main/wireprotocol/auth/FileAuthentication.java
- accio-tests/src/test/java/io/accio/testing/TestMetadataQuery.java
If user doesn't assign any authentication file, don't send the password message to client.
> Disable Authentication if no auth file assigned

- accio-main/src/main/java/io/accio/main/wireprotocol/Portal.java
- accio-main/src/main/java/io/accio/main/wireprotocol/PostgresWireProtocol.java
- accio-main/src/main/java/io/accio/main/wireprotocol/PreparedStatement.java
- accio-main/src/main/java/io/accio/main/wireprotocol/WireProtocolSession.java
- accio-main/src/main/java/io/accio/main/wireprotocol/patterns/PostgreSqlRewriteUtil.java
- accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
The level 1 prepared statement can't be reused when trying to bind it again.
Metadata Query shouldn't be bound when `parse` phase. All prepared statement should be bound when `bind` phase.
This PR also refactor the query flow.
> Fix reuse the level 1 prepared statement flow

- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Analysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestStatementAnalyzer.java
- accio-main/src/main/java/io/accio/main/web/AnalysisResource.java
- accio-main/src/main/java/io/accio/main/web/dto/SqlAnalysisOutputDto.java
- accio-tests/src/test/java/io/accio/testing/TestAnalysisResource.java
Enhance the SQL analysis API for analyzing `LIMIT` and `ORDER BY` part.
```
GET /v1/analysis/sql
```
```json
{
"sql": "SELECT * FROM Model_Customer WHERE customer_id = 1 order by customer_id desc limit 100"   
}
```
```json
[
{
"columnPredicates": [
{
"columnName": "customer_id",
"predicates": [
{
"operator": "=",
"value": "1"
}
]
}
],
"limit": "100",
"modelName": "Model_Customer",
"ordering": [
{
"direction": "DESCENDING",
"identifier": "customer_id"
}
]
}
]
```
> Analyze the limit and ordering for SQL analysis API

- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Analysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/RelationId.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Scope.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
To support the more complex SQL analysis, we should enhance the SQL analysis firstly.
- Collect all scope info for each node to a map. It's useful for generating the rewrite plan in the future.
- Assign the relation Id for every scope.
> Enhance the scope analysis in StatementAnalyzer

- docker/Dockerfile
azul/zulu-openjdk:11.0.14 only has amd64, but 11.0.22 has `arm64`.
> Upgrade azul/zulu-openjdk from 11.0.14 to 11.0.22 for arm64

- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/MetricSqlRender.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Analysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/ExpressionAnalysis.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModel.java
- accio-tests/src/test/java/io/accio/TestBigQuerySqlConverter.java
Redefine the access behavior of dynamic metric accessing. Given a sample manifest:
```JSON
{
"name": "Revenue",
"baseObject": "Orders",
"dimension": [
{
"name": "custkey",
"type": "integer"
},
{
"name": "orderdate",
"type": "date"
}
],
"measure": [
{
"name": "totalprice",
"type": "integer",
"expression": "sum(totalprice)"
}
],
"timeGrain": [
{
"name": "orderdate",
"refColumn": "orderdate",
"dateParts": [
"YEAR",
"MONTH"
]
}
]
}
```
Some behaviors were changed.
```SQL
SELECT totalprice FROM Revenue
```
```SQL
WITH Revenue AS (
SELECT 
sum(totalprice) as totalprice
FROM Orders
)
SELECT totalprice FROM Revenue
```
```sql
SELECT count(*) FROM Revenue
```
```SQL
WITH Revenue AS (
SELECT
custkey,
orderdate,
sum(totalprice) as totalprice
FROM Orders
GROUP BY 1, 2
)
SELECT count(*) FROM Revenue …
```
> Fix the accessing behavior for metric or model in the dynamic access mode

- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetricViewSqlRewrite.java
- accio-server/src/main/java/io/accio/server/module/PostgresConnectorModule.java
We tried to make PostgreSQL as data source and use Metabase to connect Accio. We found some issues.
PgMetastore should bind DuckDBMetadata not PostgresMetadata. Although the Data source is PostgreSQL, the metastore still uses DuckDB in our design.
Metabase will send a statement like `select * from "orders"` to Accio. But Accio remove the quoted when the rewriter rewrite. We should not change the quoted delimited status.
> Fix for PostgreSQL as data source

- accio-main/src/main/java/io/accio/main/PreviewService.java
- accio-main/src/main/java/io/accio/main/web/MDLResource.java
- accio-main/src/main/java/io/accio/main/web/dto/PreviewOutputDto.java
- accio-tests/src/test/java/io/accio/testing/RequireAccioServer.java
- accio-tests/src/test/java/io/accio/testing/TestMDLResource.java
To make user can be more easier to use the preview data API. This PR adds the column metadata for the result set.
Given a input
```json
{
"manifest" : {
"catalog": "canner-cml",
"schema": "tpch_tiny",
"models": [
{
"refSql": "select * from \"canner-cml\".\"tpch_tiny\".\"orders\"",
"columns": [
{
"name": "o_orderkey",
"type": "integer"
},
{
"name": "o_orderdate",
"type": "date"
}
]
}
]
},
"sql": "select o_orderkey, o_orderdate from Orders",
"limit": 20
}
```
The output for the preview will be
```json
{
"columns": [
{
"name": "o_orderkey",
"type": "int8"
},
{
"name": "o_orderdate",
"type": "date"
}
],
"data": [
[
37315,
"1992-06-06"
],
[
36485,
"1992-06-06"
],
...
}
}
```
> Provide result set metadata in Preview data result

- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioPlanner.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/GenerateViewRewrite.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/WithRewriter.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetricViewSqlRewrite.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestView.java
This PR allows user to query views in dynamic access mode. The statement of view will be used to create a CTE. Every behavior of dynamic accessing only apply on the internal statement.
When dynamic accessing is enable, given view and metric
```
metric CountOrders @baseObject(Orders) {
custkey: integer @dim
orderstatus: varchar @dim
totalprice: integer @measure(sum(totalprice))
}
view {
"selectAll": "select * from CountOrders",
"selectOneDim": "select custkey from CountOrders"
}
```
Query a SQL
```
select custkey from selectAll
```
The CountOrders will be grouped by all dimension, `custkey` and `orderstatus`.
Query another SQL
```
select custkey from selectOneDim
```
The CountOrders will be grouped by `custkey`.
> Support query view in dynamic access mode

- accio-base/src/main/java/io/accio/base/config/ConfigManager.java
- accio-tests/src/test/java/io/accio/testing/TestConfigResource.java
We don't have a way to reload the cache service now. Make them be static to avoid other side effect.
> Make CacheService-related configs be static 

- accio-base/src/main/java/io/accio/base/AccioMDL.java
- accio-base/src/main/java/io/accio/base/dto/Model.java
- accio-base/src/main/java/io/accio/base/dto/TableReference.java
- accio-base/src/main/java/io/accio/base/sqlrewrite/ModelSqlRender.java
- accio-base/src/test/java/io/accio/base/dto/TestManifestSerDe.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/AbstractTestFramework.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/AbstractTestModel.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModelRefSql.java
- accio-base/src/test/java/io/accio/base/sqlrewrite/TestModelTableReference.java
- accio-main/src/test/java/io/accio/main/pgcatalog/builder/TestCreateBigQueryTempTable.java
- accio-tests/src/test/resources/bigquery/TestWireProtocolWithBigquery.json
To optimize the SQL easily, we provide a new way to build a model. `TableReference` is build from `catalog`, `schema` and `table` which point to the physical table in the datasource. Instead of `refSql`, we can accurately to set which columns the SQL actually used.  This way make data source side can optimize the SQL plan more easily.
```
{
"tableReference: {
"catalog": "memory",
"schema": "tpch",
"table": "orders"
},
columns: [
...
]
}
```
> Add TableReference field for Model to optimize the query projection

- wren-base/src/main/java/io/wren/base/client/duckdb/FileUtil.java
- wren-base/src/main/java/io/wren/base/config/ConfigManager.java
- wren-main/src/main/java/io/wren/main/WrenManager.java
- wren-main/src/main/java/io/wren/main/connector/duckdb/DuckDBMetadata.java
- wren-main/src/main/java/io/wren/main/wireprotocol/PgMetastoreImpl.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResource.java
- Hide the stack trace when cache isn't supported
- To simplify the server start message, show the exception stack trace when log level is debug only.
- Unify the name of archive folder to `archived`.
> Optimize the behavior of server deploying

- .github/workflows/build-dev-image.yml
- .github/workflows/deploy.yml
- .github/workflows/stable-release.yml
- Add `nightly` tag for nightly build.
- disable the push tag event for deploy to canner maven repo.
- Add stable release flow
- The stable release will build a image and tag it with given tag and `latest`.
- When trigger the flow, we can assign a specific tag or use default value. The default value is the current version number plus a patch number.  
- I've test this workflow in my personal repo. 
- I've test this workflow in this repo.
> Refine the release and deploy flow

- example/duckdb-tpch-example/etc/config.properties
Wrong path example for session-sql
> Fix typo in config.properties

- wren-base/src/main/java/io/wren/base/client/duckdb/DuckdbClient.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWireProtocolWithDuckDB.java
The original workaround is very expensive. In the original DuckDB behavior, it doesn't support describing a query that contains any parameters in select items. Mostly, the parameter is used for filtering or other purposes. It's not worth supporting this kind of query and then trying to use an expensive method.
```sql
SELECT orderkey FROM Orders WHERE orderkey = ?
```
```sql
SELECT ?, orderkey FROM Orders
```
- Support selecting parameter items.
> Describe query followed the behavior of DuckDB

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/Analysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/SemanticExceptions.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/TestAllRulesRewrite.java
- Support Subquery expression
```sql
SELECT * FROM Orders WHERE orderkey in (SELECT orderkey FROM Lineitem)
```
- Support [Set Operation](https://trino.io/docs/current/sql/select.html#set-operations)
```sql
SELECT * FROM Orders WHERE orderkey < 5 union SELECT * FROM Orders WHERE orderkey > 10;
```
> Support set operations and subquery expression

- wren-main/src/main/java/io/wren/main/connector/bigquery/BigQuerySqlConverter.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestBigQuerySqlConverter.java
It's the legacy rewrite rule for BigQuery as the PG wire protocol engine. Currently, all of metadata query have been executed by PgMetastore (DuckDB). The rule has some issue will impact some subquery syntax. For example
```sql
SELECT DISTINCT f.Lname FROM Faculty f JOIN Member_of m ON f.FacID = m.FacID WHERE m.DNO = (SELECT DNO FROM Department WHERE Dname = 'Computer Science');
```
> Remove legacy decorrelate rewrite for BigQuery

- wren-main/src/main/java/io/wren/main/sqlglot/SQLGlot.java
- wren-sqlglot-server/main.py
- wren-tests/src/test/java/io/wren/testing/sqlglot/TestSQLGlotConverter.java
- wren-tests/src/test/java/io/wren/testing/sqlglot/TestTPCHWithDuckDB.java
- wren-tests/src/test/java/io/wren/testing/sqlglot/TestTPCHWithSnowflake.java
After testing, we found the `sqlglot` python could be pre-load by calling function before concurrent requests to avoid deadlock when the python runtime loading module. And can not use the `SELECT 1` simple statement, should use `SELECT ARRAY[1,2,3][1]` a little complicated statement.
> Fix SQLGlot deadlock via pre-load python module

- wren-main/src/main/java/io/wren/main/PreviewService.java
- wren-main/src/main/java/io/wren/main/web/MDLResource.java
- wren-main/src/main/java/io/wren/main/web/dto/DryPlanDto.java
- wren-tests/src/test/java/io/wren/testing/RequireWrenServer.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResource.java
Provide a API to get the result metadata or inner SQL without executing.
Get the result metadata without executing SQL
```
GET /v1/mdl/dry-run
```
```
{
"manifest" : {
"catalog": "canner-cml",
"schema": "tpch_tiny",
"models": [
{
"refSql": "select * from \"memory\".\"tpch\".\"orders\"",
"columns": [
{
"name": "o_orderkey",
"type": "integer"
},
{
"name": "o_orderdate",
"type": "date"
}
]
}
]
},
"sql": "select \"o_orderkey\", \"o_orderdate\" from \"Orders\" wehre \"o_orderdate\" > ?",
}
```
- `manifest`: It's optional. If we don't carry it, use deployed MDL in default.
- `sql`: It's required. The sql will be dry-run.
Get the dry-planned SQL which is a SQL can be executed in the data source side.
```
GET /v1/mdl/dry-plan
```
```
{
"manifest" : {
"catalog": "canner-cml", …
```
> Provide API for SQL Dry-Run and Dry-Plan

- wren-base/src/main/java/io/wren/base/WrenMDL.java
- wren-main/src/main/java/io/wren/main/pgcatalog/PgCatalogManager.java
- wren-main/src/main/java/io/wren/main/wireprotocol/PgMetastoreImpl.java
- wren-tests/src/test/java/io/wren/testing/bigquery/AbstractWireProtocolTestWithBigQuery.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestResultSetMetadata.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolWithBigquery.java
- wren-tests/src/test/resources/bigquery/TestResultSetMetadata.json
- wren-tests/src/test/resources/bigquery/TestWireProtocolWithBigquery.json
To get the view metadata by PG wire protocol, we should create the mock table in pg metastore.
- Describe view statement and create table in pg_catalog
- Remove legacy metadata schema name.
- Get wrong type by JDBC column metadata
> Create view metadata in pg_catalog

- wren-base/src/main/java/io/wren/base/WrenMDL.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionTypeAnalyzer.java
- wren-main/src/main/java/io/wren/main/pgcatalog/PgCatalogManager.java
- wren-main/src/main/java/io/wren/main/web/LineageResource.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolWithBigquery.java
BigQuery connector will trigger the type coercion rewrite. We should handle the get column type of view. However, we didn't store the metadata of view. Currently, return empty result for view.
> Fix query view with filter for bigquery connector

- .github/workflows/integration-tests.yml
- .github/workflows/stable-release.yml
`ubuntu-latest` uses java 11 in default. We should set up java 21 before executing maven command.
> Set up JDK 21 before preparing release

- wren-shaded/pom.xml
Due to the stable release be failed. We should remove the legacy validation dependency.
> Remove legacy validation dependency

- wren-base/src/main/java/io/wren/base/client/duckdb/DuckdbTypes.java
- wren-base/src/main/java/io/wren/base/type/PGTypes.java
- wren-main/src/main/java/io/wren/main/WrenManager.java
- wren-main/src/main/java/io/wren/main/pgcatalog/PgCatalogManager.java
- wren-main/src/main/java/io/wren/main/pgcatalog/exception/DeployException.java
- wren-tests/src/test/java/io/wren/testing/duckdb/AbstractWireProtocolTestWithDuckDB.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestDeployDuckDBRuntime.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWireProtocolWithDuckDB.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenTypeDeploy.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDB.java
- add missing type mapping for PGType to DuckDB Type
- Handle the error for known pg type which don't supported by DuckDB
- Return http 400 error when mdl deploying failed.
> Fix the DuckDB type mapping and enhance the error handling for MDL deploying

- wren-base/src/main/java/io/wren/base/config/PostgresWireProtocolConfig.java
- wren-cache/src/main/java/io/wren/cache/CacheManager.java
- wren-cache/src/main/java/io/wren/cache/CacheManagerImpl.java
- wren-cache/src/main/java/io/wren/cache/CacheModule.java
- wren-cache/src/main/java/io/wren/cache/NoOpCacheManager.java
- wren-main/src/main/java/io/wren/main/WrenModule.java
- wren-main/src/main/java/io/wren/main/pgcatalog/NoOpPgCatalogManager.java
- wren-main/src/main/java/io/wren/main/pgcatalog/PgCatalogManagerImpl.java
- wren-server/src/main/java/io/wren/server/WrenServer.java
- wren-server/src/main/java/io/wren/server/module/BigQueryConnectorModule.java
- wren-server/src/main/java/io/wren/server/module/DuckDBConnectorModule.java
- wren-server/src/main/java/io/wren/server/module/PostgresWireProtocolModule.java
- wren-server/src/main/java/io/wren/server/module/WebModule.java
- wren-tests/pom.xml
- wren-tests/src/main/java/io/wren/testing/TestingWrenServer.java
- wren-tests/src/test/java/io/wren/testing/TestConfigResource.java
- wren-tests/src/test/java/io/wren/testing/TestMetadataQuery.java
- wren-tests/src/test/java/io/wren/testing/bigquery/AbstractCacheTest.java
- wren-tests/src/test/java/io/wren/testing/bigquery/AbstractWireProtocolTestWithBigQuery.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestDeployBigQueryRuntime.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestDuckdbRetryCacheTask.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestDynamicFields.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolTypeWithBigQuery.java
- wren-tests/src/test/java/io/wren/testing/duckdb/AbstractWireProtocolTestWithDuckDB.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWireProtocolTypeWithDuckDB.java
- wren-tests/src/test/java/io/wren/testing/postgres/AbstractWireProtocolTestWithPostgres.java
- wren-tests/src/test/java/io/wren/testing/postgres/TestDeployPostgresRuntime.java
- wren-tests/src/test/java/io/wren/testing/postgres/TestWireProtocolTypeWithPostgres.java
- wren-tests/src/test/java/io/wren/testing/snowflake/AbstractWireProtocolTestWithSnowflake.java
- wren-tests/src/test/java/io/wren/testing/snowflake/TestWireProtocolTypeWithSnowflake.java
The Wren protocol and cache aren't necessary for the WrenAI user. Some logs or the internal DuckDB may make them be confused. Let's make Wren Protocol be configurable and disable in default.
We can use the new config to enable it.
- `pg-wire-protocol.enabled`: enable the wren protocol and cache layer. Default is false.
> Disable the Wren Protocol and cache layer in default

- trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
- wren-tests/src/test/java/io/wren/testing/AbstractFunctionTest.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestFunctionBigQuery.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestFunctionDuckDB.java
- wren-tests/src/test/java/io/wren/testing/postgres/TestFunctionPostgres.java
We follow [the supported function list of Trino](https://trino.io/docs/current/functions/list.html) to add a test for wren engine function supporting. In this PR, we only test `BigQuery`, `DuckDB` and `Postgres`. If a function or operator is supported by all of them, we say that it's a supported function by Wren Engine. 
BTW, We comment out the unsupported function in the test for taking a note.
- Add test for each data source.
- Fix the timestamp literal for DuckDB
> Add function test and fix timestamp in DuckDB

- ibis-server/data_source.py
- ibis-server/dto.py
Encounter error when executed the sql statement generated from dry-plan API
`psycopg2.errors.UndefinedTable: relation "public.orders" does not exist
LINE 1: ...totalprice" AS "o_totalprice" FROM (SELECT * FROM "public"."...`
The statement dry-plan generated
`WITH "public_orders" AS (SELECT "public_orders"."o_clerk" AS "o_clerk", "public_orders"."o_comment" AS "o_comment", "public_orders"."o_custkey" AS "o_custkey", "public_orders"."o_orderdate" AS "o_orderdate", "public_orders"."o_orderkey" AS "o_orderkey", "public_orders"."o_orderpriority" AS "o_orderpriority", "public_orders"."o_orderstatus" AS "o_orderstatus", "public_orders"."o_shippriority" AS "o_shippriority", "public_orders"."o_totalprice" AS "o_totalprice" FROM (SELECT "public_orders"."o_clerk" AS "o_clerk", …
> fix(Ibis-server): add database to connection info

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/DecisionPointAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestDecisionPointAnalyzer.java
Previously, submit the sql:
```
select name, count(*) from customer group by 1
```
We will get
```
{
"groupByKeys": [1, "name"]
}
```
However, we expected to get only `name`.
> Add GroupByKey without index literal in DecisionPointAnalyzer Result

- wren-base/src/main/java/io/wren/base/jinjava/JinjavaExpressionProcessor.java
- wren-base/src/test/java/io/wren/base/dto/TestMacro.java
- wren-base/src/test/java/io/wren/base/jinjava/TestJinjavaExpressionProcessor.java
- Fix the issue about macro can't accept a function call. Defining a column with an expression below will be failed.
```
{{ MoM('sum(order_items.Price)') }}
```
Some spec is changed. Currently, a Jinjava expression only accept `Identifier` and `FunctionCall`. 
Some acceptable cases:
- `{{ para_1 }}`
- `{{ fn(para_1) }}`
- `{{ fn('col_1') }}`
- `{{ fn('sum(co_1)') }}`
Some unacceptable case:
- `{{ para_1 + para2 }}` should be `{{ para_1 }} + {{ para_2 }}`
- `{{ fn1() + fn2() }}` should be `{{ fn1() }} + {{ fn2() }}`
- Used SQL parser to handle the jinjava expression.
- Enhance the error message.
> Fix the macro parameter can't accept a function call string

- .github/workflows/build.yml
- .github/workflows/integration-tests.yml
We're going to redesign wren engine. The tests of Engine V1 (implemented by pure java) will only be triggered by the PR labeled `v1-engine-changed`.
> Run v1-engine test when labeled `v1-engine-changed` only

- ibis-server/Makefile
- ibis-server/README.md
- ibis-server/app/main.py
- ibis-server/pyproject.toml
Because fastapi release [0.111.0](https://github.com/tiangolo/fastapi/releases/tag/0.111.0) include the [FastAPI CLI](https://fastapi.tiangolo.com/fastapi-cli/). We can use the CLI to start the fastapi service.
> Adjust with fastapi cli

- wren-base/src/main/java/io/wren/base/sqlrewrite/Utils.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/Field.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/DecisionPointAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/DecisionPointContext.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/QueryAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestDecisionPointAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestStatementAnalyzer.java
- wren-main/src/main/java/io/wren/main/web/AnalysisResource.java
- wren-main/src/main/java/io/wren/main/web/dto/QueryAnalysisDto.java
- wren-tests/src/test/java/io/wren/testing/TestAnalysisResource.java
To provide more clear information of the join relation, analysis API provide the source dataset(e.g. model or metric) for all expression used by the join criteria. If an expression doesn't belong any dataset, it won't be added in the list.
`GET` /v1/analysis/sql
```json
{
"manifest": {
"catalog": "test",
"schema": "test",
"models": [
{
"name": "Customer",
"refSql": "select * from tpch.customer",
"columns": [
{
"name": "custkey",
"type": "integer",
"expression": "c_orderkey"
},
{
"name": "name",
"type": "varchar",
"expression": "c_name"
}
],
"primaryKey": "custkey"
},
{
"refSql": "select * from tpch.orders",
"columns": [
{
"name": "orderkey",
"type": "integer",
"expression": "o_orderkey"
},
{
"name": "custkey",
"type": "integer",
"expression": "o_custkey"
},
{
"name": …
```
> Analyze the source dataset of the expression in the join criteria in the decision point API

- ibis-server/app/config.py
- ibis-server/app/logger.py
- ibis-server/app/routers/ibis.py
I added a `logger.py` to wrap the `logging` for basic config like log level could be one side.
Before we import logging then use `getLogger(name)`, we should from `app.logger` import `get_logger` instead of it.
> Add logger

- ibis-server/app/model/dto.py
- wren-main/src/main/java/io/wren/main/web/MDLResourceV2.java
- wren-tests/src/test/java/io/wren/testing/RequireWrenServer.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResource.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResourceV2.java
- wren-tests/src/test/java/io/wren/testing/duckdb/AbstractWireProtocolTestWithDuckDB.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestDeployDuckDBRuntime.java
Before the manifest string was a JSON string, but it could have some issues about escaping character.
Making the string base64 may be better.
> Adjust manifest string to base64

- pom.xml
- wren-base/src/main/java/io/wren/base/client/duckdb/DuckdbClient.java
- wren-base/src/main/java/io/wren/base/type/IntervalType.java
- wren-main/src/main/java/io/wren/main/wireprotocol/WireProtocolSession.java
- wren-tests/src/test/java/io/wren/testing/TestMetadataQuery.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestResultSetMetadata.java
- wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolWithBigquery.java
DuckDB v0.10.3 changed some behavior:
- https://github.com/duckdb/duckdb/pull/11746: The oid of pg type is correct now.
- https://github.com/duckdb/duckdb-java/issues/18: There're some issue for auto-load in Java API.
> Upgrade DuckDB to v0.10.3

- ibis-server/app/model/connector.py
- ibis-server/app/model/dto.py
- ibis-server/app/routers/ibis/bigquery.py
- ibis-server/app/routers/ibis/postgres.py
- ibis-server/app/routers/ibis/snowflake.py
- ibis-server/poetry.lock
- ibis-server/pyproject.toml
- ibis-server/tests/routers/ibis/test_bigquery.py
- ibis-server/tests/routers/ibis/test_postgres.py
- ibis-server/tests/routers/ibis/test_snowflake.py
We will convert types in the data frame by input dtypes.
We also format datetime to a formatted string.
```
POST /v2/ibis/postgres/query
{
"connectionInfo": {...},
"manifestStr": "base64 string of manifest",
"sql": 'SELECT * FROM "Orders" LIMIT 1',
"columnDtypes": {
"totalprice": "float",
"orderdate": "datetime64",
"timestamp": "datetime64",
"timestamptz": "datetime64"
}
}
```
```diff
{
"columns": [
"orderkey",
"custkey",
"orderstatus",
"totalprice",
"orderdate",
"order_cust_key",
"timestamp",
"timestamptz"
],
"data": [
[
1,
370,
"O",
"172799.49",
-           820540800000,
+           "1996-01-02 00:00:00.000000",
"1_370",
-           1704153599000,
+           "2024-01-01 23:59:59.000000",
-           1704153599000
+           "2024-01-01 23:59:59.000000 UTC"
]
],
"dtypes": {
"orderkey": …
```
> Add column_dtypes to forcibly convert the type

- .github/workflows/ibis-ci.yml
- ibis-server/.pre-commit-config.yaml
- ibis-server/Makefile
- ibis-server/README.md
- ibis-server/app/config.py
- ibis-server/app/logger.py
- ibis-server/app/mdl/rewriter.py
- ibis-server/app/model/connector.py
- ibis-server/app/model/data_source.py
- ibis-server/app/model/dto.py
- ibis-server/app/routers/ibis/bigquery.py
- ibis-server/app/routers/ibis/postgres.py
- ibis-server/app/routers/ibis/snowflake.py
- ibis-server/poetry.lock
- ibis-server/pyproject.toml
- ibis-server/tests/routers/ibis/test_bigquery.py
- ibis-server/tests/routers/ibis/test_postgres.py
- ibis-server/tests/routers/ibis/test_snowflake.py
Add ruff for lint and format.
Add pre-commit to check lint and format.
Add action to check lint and format.
> Add ruff for python CI flow

- wren-modeling-rs/core/Cargo.toml
- wren-modeling-rs/core/src/logical_plan/context_provider.rs
- wren-modeling-rs/core/src/logical_plan/rule.rs
- wren-modeling-rs/core/src/logical_plan/utils.rs
- wren-modeling-rs/core/src/mdl/lineage.rs
- wren-modeling-rs/core/src/mdl/manifest.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/core/src/mdl/utils.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/sqllogictest/test_sql_files/model.slt
- wren-modeling-rs/sqllogictest/tests/resources/ecommerce/customers.csv
- wren-modeling-rs/sqllogictest/tests/resources/ecommerce/order_items.csv
- wren-modeling-rs/sqllogictest/tests/resources/ecommerce/orders.csv
- In this PR, instead of bare table reference,  we uses full table reference to analyze MDL.
- If physical table resource is exists, we should `DefaultTableSource` instead of `LogicalTableSource`. Refer to [TableSource](https://datafusion.apache.org/library-user-guide/building-logical-plans.html#table-sources)
- Column expression can't work well.
> Fix the table qualified name and executable plan for DataFusion

- .github/workflows/ibis-ci.yml
We found sometimes we will modify the Java codebase at the same time as modifying ibis.
So we should build the jar to make sure the Java engine is the latest.
> Make CI to build executable jar

- ibis-server/app/model/connector.py
- ibis-server/app/model/data_source.py
- ibis-server/app/routers/v2/ibis/__init__.py
- ibis-server/app/routers/v2/ibis/bigquery.py
- ibis-server/app/routers/v2/ibis/mysql.py
- ibis-server/app/routers/v2/ibis/postgres.py
- ibis-server/poetry.lock
- ibis-server/pyproject.toml
- ibis-server/tests/routers/ibis/test_mysql.py
Make `POST /v2/ibis/{data_source}/query` support new data source `MySQL`
- host: string, `required`
- port: integer, `required`
- user: string, `required`
- password: string, `required`
- database: string, `required`
or
- connectionUrl: string, `required`
```json
{
"sql": "select * from \"Orders\" limit 1",
"manifestStr": "eyJjYXRhbG9nIjoibXlfY2F0YWxvZyIsInNjaGVtYSI6Im15X3...",
"host": "localhost",
"port": 3306,
"database": "dbname",
"user": "username",
"password": "password"
}
}
```
or
```json
{
"sql": "select * from \"Orders\" limit 1",
"manifestStr": "eyJjYXRhbG9nIjoibXlfY2F0YWxvZyIsInNjaGVtYSI6Im15X3...",
"connectionUrl": "mysql://username:password@localhost:3306/dbname"
}
}
```
- columns
- data
- dtypes: Type through the pandas
```json
{ …
```
> Support new data source MySQL

- ibis-server/Dockerfile
We don't use the rust in the normal flow. We can remove the failed builder for rust in the Dockerfile now.
> Remove rust in Dockerfile

- wren-modeling-py/Cargo.lock
- wren-modeling-py/Cargo.toml
- wren-modeling-py/build.rs
Cargo build will be failed in the MacOS before.
This project needs to add `pyo3-build-config`.
Reference
https://pyo3.rs/v0.14.2/building_and_distribution.html#macos
> Add pyo3-build-config for macos building

- wren-modeling-py/Cargo.lock
- wren-modeling-py/src/errors.rs
- wren-modeling-py/src/lib.rs
- wren-modeling-py/tests/test_modeling_core.py
- wren-modeling-rs/Cargo.toml
- wren-modeling-rs/core/Cargo.toml
- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/logical_plan/context_provider.rs
- wren-modeling-rs/core/src/logical_plan/utils.rs
- wren-modeling-rs/core/src/mdl/builder.rs
- wren-modeling-rs/core/src/mdl/lineage.rs
- wren-modeling-rs/core/src/mdl/manifest.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/core/src/mdl/utils.rs
- wren-modeling-rs/core/tests/data/mdl.json
- wren-modeling-rs/sqllogictest/bin/sqllogictests.rs
- wren-modeling-rs/sqllogictest/src/engine/runner.rs
- wren-modeling-rs/sqllogictest/src/lib.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/sqllogictest/test_sql_files/model.slt
- wren-modeling-rs/wren-example/Cargo.toml
- wren-modeling-rs/wren-example/examples/datafusion-apply.rs
- wren-modeling-rs/wren-example/examples/plan-sql.rs
- wren-modeling-rs/wren-example/examples/to-many-calculation.rs
- Upgrade Datafusion to v39.0.0
- Introduce the TO_MANAY calculation
- Enhance the error handling: stop to panic and throw DataFusionError instead.
- Fix and enhance the testing
- The generated logical plan can't apply to DataFusion directly. Currently, I use a workaround to run the SQL by DataFusion.
- Generated the SQL by `WrenMDL#transform_sql`
- Execute the generated SQL by DataFusion.
> Introduce the calculation for TO_MANY relationship

- .github/workflows/ibis-ci.yml
- ibis-server/README.md
- ibis-server/app/model/__init__.py
- ibis-server/app/model/data_source.py
- ibis-server/poetry.lock
- ibis-server/pyproject.toml
- ibis-server/tests/routers/ibis/test_mssql.py
Make `POST /v2/ibis/{data_source}/query` support new data source `MS SQL Server`
- host: string, `required`
- port: integer, `required`
- database: string, `required`
- user: string, `required`
- password: string, `required`
- driver: string,
> [!WARNING]
> Ibis does not support mssql using connection url. Follow https://github.com/ibis-project/ibis/issues/9415
```json
{
"sql": "select * from \"Orders\" limit 1",
"manifestStr": "eyJjYXRhbG9nIjoibXlfY2F0YWxvZyIsInNjaGVtYSI6Im15X3...",
"host": "localhost",
"port": 1433,
"database": "dbname",
"user": "username",
"password": "password"
}
}
```
- columns
- data
- dtypes: Type through the pandas
```json
{
"columns": [
"o_orderkey",
"o_custkey",
"o_orderstatus",
"o_totalprice",
"o_orderdate",
"o_orderpriority",
"o_clerk", …
```
> Add data source MS SQL Server

- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/logical_plan/context_provider.rs
- wren-modeling-rs/core/src/mdl/builder.rs
- wren-modeling-rs/core/src/mdl/lineage.rs
- wren-modeling-rs/core/src/mdl/utils.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/sqllogictest/test_sql_files/model.slt
- wren-modeling-rs/wren-example/examples/datafusion-apply.rs
- wren-modeling-rs/wren-example/examples/plan-sql.rs
- wren-modeling-rs/wren-example/examples/to-many-calculation.rs
- Rename the default schema from `default` to `public` because the `default` is a SQL reserved word.
- Fix the calculation expression for the relationship expression and normal expression (e.g. `a.b.c1 + a1`)
- Enhance the testing for relationship
> Fix the complex calculated field and rename the default schema

- ibis-server/app/model/connector.py
- ibis-server/app/routers/v2/ibis.py
- ibis-server/tests/routers/ibis/test_postgres.py
Add new query parameter `limit` for query API to limit data size.
POST /v2/ibis/{data_source}/query?`limit=1`
> Add query parameter limit

- ibis-server/tests/routers/ibis/test_clickhouse.py
- trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
- trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
- wren-base/src/main/java/io/wren/base/config/WrenConfig.java
- wren-main/src/main/java/io/wren/main/PreviewService.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResource.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResourceV2.java
Close #647 
The join relation with brackets is valid for Trino but isn't for Clickhouse.
```
SELECT *
FROM (
a
INNER JOIN b ON (a.x = b.y)
)
```
Because `ibis` can't handle the syntax for Clickhouse, we have stopped generating the join syntax with brackets in this PR.
```
SELECT *
FROM
a
INNER JOIN b ON (a.x = b.y)
```
- Currenlty, `dynamic-query` will be enable by default for wren-engine.
> Remove redundent brackets for the join syntax

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/DecisionPointAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/FilterAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/FilterAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/QueryAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestDecisionPointAnalyzer.java
- wren-main/src/main/java/io/wren/main/web/AnalysisResource.java
- wren-main/src/main/java/io/wren/main/web/dto/NodeLocationDto.java
- wren-main/src/main/java/io/wren/main/web/dto/QueryAnalysisDto.java
- wren-tests/src/test/java/io/wren/testing/TestAnalysisResource.java
Add `nodeLocation` property for the SqlAnalysis result:
- `selectItems`
- `relation`
- `filter`
- `sortItem`
- `GroupByKey`
- `ExprSource`
```sql
SELECT custkey, name FROM customer ORDER BY 1 ASC, 2 DESC
```
```json
[
{
"selectItems":[
{
"alias":null,
"expression":"custkey",
"properties":{
"includeMathematicalOperation":"false",
"includeFunctionCall":"false"
},
"nodeLocation":{
"line":1,
"column":8
}
},
{
"alias":null,
"expression":"name",
"properties":{
"includeMathematicalOperation":"false",
"includeFunctionCall":"false"
},
"nodeLocation":{
"line":1,
"column":17
}
}
],
"relation":{
"type":"TABLE",
"tableName":"customer",
"nodeLocation":{
"line":1,
"column":27
}
},
"groupByKeys":[
],
"sortings":[
{
"expression":"custkey",
"ordering":"ASCENDING",
"nodeLocation":{
"line":1,
"column":45
} …
```
> Add node location info for SQL analysis result

- .github/workflows/ibis-ci.yml
We're still consistently encountering an issue where JAVA or Rust code modifications affect the ibis-server, but this isn't being detected in the Pull Request CI.
> Make ibis CI for each PR

- ibis-server/tests/routers/ibis/test_clickhouse.py
- trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
- trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
- wren-main/src/main/java/io/wren/main/web/dto/QueryAnalysisDto.java
- wren-tests/src/test/java/io/wren/testing/TestAnalysisResource.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDB.java
Expect `Clickhouse`, the most data source support the alias join relation. However, we remove the brackets in #649. It will cause some problem when someone use alias join in other connector.
The followed SQL should be valid in non-clickhouse:
```sql
SELECT orderstatus FROM ("Orders" o JOIN "Customer" c ON o.custkey = c.custkey) j1 LIMIT 1
```
It's also hard to implement for sqlglot https://github.com/tobymao/sqlglot/issues/3735#issuecomment-2208028722
We needs to avoid this syntax ASAP.
- Fix the SQL analysis tests in 2cd455d
> Fix the alias join for Non-Clickhouse connector

- ibis-server/app/logger.py
- ibis-server/app/mdl/rewriter.py
- ibis-server/app/model/__init__.py
- ibis-server/app/model/connector.py
- ibis-server/app/model/metadata/dto.py
- ibis-server/app/routers/v2/ibis.py
- ibis-server/poetry.lock
- ibis-server/pyproject.toml
- ibis-server/tests/routers/ibis/test_postgres.py
- ibis-server/tests/routers/test_ibis.py
Add two APIs for the dry plan
One API only rewrites SQL with manifest
```
POST /v2/ibis/dry-plan
{
"manifestStr": "eyJjYXRhbG9nIjoibXlfY2F0YWxvZyIsInN......",
"sql": "SELECT orderkey, order_cust_key FROM \"Orders\" LIMIT 1"
}
```
```
WITH
"Orders" AS (
SELECT
"Orders"."orderkey" AS "orderkey",
"Orders"."custkey" AS "custkey",
"Orders"."order_cust_key" AS "order_cust_key"
FROM
(
SELECT
"Orders"."orderkey" AS "orderkey",
"Orders"."custkey" AS "custkey",
"Orders"."order_cust_key" AS "order_cust_key"
FROM
(
SELECT
o_orderkey AS "orderkey",
o_custkey AS "custkey",
CONCAT (o_orderkey, '_', o_custkey) AS "order_cust_key"
FROM
(
SELECT
o_orderkey,
o_custkey
FROM
public.orders
) AS "Orders"
) AS "Orders"
) AS "Orders"
)
SELECT
orderkey,
order_cust_key
FROM
"Orders"
LIMIT
1
```
Another API will …
> Add dry-plan

- ibis-server/.pre-commit-config.yaml
- ibis-server/README.md
- ibis-server/app/model/__init__.py
- ibis-server/app/model/data_source.py
- ibis-server/justfile
- ibis-server/poetry.lock
- ibis-server/pyproject.toml
- ibis-server/tests/routers/v2/connector/test_trino.py
- ibis-server/tests/self_testcontainers/trino/__init__.py
Make `POST /v2/connector/{data_source}/query` support new data source `trino`
- host: string, `required`
- port: integer, `required`
- catalog: string, `required`
- schema: string, `required`
- user: string, `required`
- password: string
```json
{
"sql": "select * from \"Orders\" limit 1",
"manifestStr": "eyJjYXRhbG9nIjoibXlfY2F0YWxvZyIsInNjaGVtYSI6Im15X3...",
"host": "localhost",
"port": 8080,
"catalog": "catalog",
"schema": "schema",
"user": "username",
"password": "password"
}
}
```
or
- connectionUrl: string, `required`
```json
{
"sql": "select * from \"Orders\" limit 1",
"manifestStr": "eyJjYXRhbG9nIjoibXlfY2F0YWxvZyIsInNjaGVtYSI6Im15X3...",
"connectionUrl": "trino://username:password@localhost:8080/catalog/schema"
}
}
```
- columns
- data
- …
> Add data source Trino

- ibis-server/app/mdl/analyzer.py
- ibis-server/app/model/__init__.py
- ibis-server/app/routers/v2/analysis.py
- ibis-server/tests/routers/v2/test_analysis.py
- wren-main/src/main/java/io/wren/main/web/AnalysisResource.java
- wren-main/src/main/java/io/wren/main/web/AnalysisResourceV2.java
- wren-main/src/main/java/io/wren/main/web/dto/SqlAnalysisInputBatchDto.java
- wren-tests/src/test/java/io/wren/testing/RequireWrenServer.java
- wren-tests/src/test/java/io/wren/testing/TestAnalysisResource.java
Implement the batch SQL analysis API
```
GET /v2/analysis/sqls
```
- `manifestStr`: based64 manifset json string.
- `sqls`: the list of input sql.
```json
{
"manifestStr": "ewogICJjYXRhbG9nIjogIndyZW5haSIsCiAgInNjaGVtYSI6ICJwdWJsaWMiLAogICJtb2RlbHMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogIm9yZGVycyIsCiAgICAgICJyZWZTcWwiOiAic2VsZWN0ICogZnJvbSBvcmRlcnMiLAogICAgICAiY29sdW1ucyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJvcmRlcmtleSIsCiAgICAgICAgICAiZXhwcmVzc2lvbiI6ICJvX29yZGVya2V5IiwKICAgICAgICAgICJ0eXBlIjogImludGVnZXIiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJjdXN0a2V5IiwKICAgICAgICAgICJleHByZXNzaW9uIjogIm9fY3VzdGtleSIsCiAgICAgICAgICAidHlwZSI6ICJpbnRlZ2VyIgogICAgICAgIH0KICAgICAgXQogICAgfSwKICAgIHsKICAgICAgIm5hbWUiOiAiY3VzdG9tZXIiLAogICAgICAicmVmU3FsIjogInNlbGVjdCAqIGZyb20gY3VzdG9tZXIiLAo …
```
> Provide the batch SQL analysis API

- ibis-server/tests/routers/v2/test_analysis.py
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/DecisionPointAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/ExprSource.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/FilterAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/FilterAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/QueryAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestDecisionPointAnalyzer.java
- wren-main/src/main/java/io/wren/main/web/AnalysisResource.java
- wren-main/src/main/java/io/wren/main/web/dto/QueryAnalysisDto.java
- wren-tests/src/test/java/io/wren/testing/TestAnalysisResource.java
We implement ExprSource analysis for the join criteria in #564. In this PR, I add this analysis for all expression items (e.g. selectItems, filter, group by keys and sorting).
```json
[
{
"selectItems": [
{
"alias": null,
"expression": "custkey",
"properties": {
"includeMathematicalOperation": "false",
"includeFunctionCall": "false"
},
"nodeLocation": {
"line": 1,
"column": 8
},
"exprSources": [
{
"expression": "custkey",
"sourceDataset": "customer",
"nodeLocation": {
"line": 1,
"column": 8
}
}
]
},
...
],
"relation": {
"type": "TABLE",
"tableName": "customer",
"nodeLocation": {
"line": 1,
"column": 37
}
},
"filter": {
"type": "EXPR",
"node": "(custkey = 1)",
"nodeLocation": {
"line": 1,
"column": 60
},
"exprSources": [
{
"expression": "custkey",
"sourceDataset": "customer", …
```
> Add ExprSource for all analysis items

- .github/workflows/ibis-ci.yml
The Trino test container is unstable, causing occasional test failures. We have split the tests until the issue is resolved.
> Make trino test independent

- ibis-server/app/model/__init__.py
- ibis-server/app/model/data_source.py
Mask all fields of connection info.
> Mask sensitive information

- wren-modeling-rs/Cargo.toml
- wren-modeling-rs/core/src/logical_plan/analyze/mod.rs
- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/analyze/relation_chain.rs
- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/mdl/lineage.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/wren-example/examples/calculation-invoke-calculation.rs
- wren-modeling-rs/wren-example/examples/plan-sql.rs
- wren-modeling-rs/wren-example/examples/to-many-calculation.rs
This PR allows the calculation to be used by another model through the relationship. Consider the case in `wren-modeling-rs/wren-example/examples/calculation-invoke-calculation.rs`:
```rust
.column(
ColumnBuilder::new("customer_state_cf", "varchar")
.calculated(true)
.expression("orders.customer_state")
.build(),
)
```
We can add a calculated field in `order_items` to access the calculated field `customer_state` in `orders`.
- Only allow one calculation in an expression currently. We will file another issue for it.
> Allow to invoke a calculation belong to another models

- trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
- trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
- trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDBTableFunction.java
Resolve #673
Follow Trino
https://github.com/trinodb/trino/pull/18256
> Show original characters for string literals instead of escaping

- wren-modeling-py/Cargo.lock
- wren-modeling-rs/Cargo.toml
- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/core/tests/data/mdl.json
- Update the API usage.
- Fix the test case.
> Upgrade DataFusion to 40.0.0

- wren-modeling-py/Cargo.lock
- wren-modeling-rs/Cargo.toml
- wren-modeling-rs/core/Cargo.toml
- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/analyze/relation_chain.rs
- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/logical_plan/context_provider.rs
- wren-modeling-rs/core/src/logical_plan/utils.rs
- wren-modeling-rs/core/src/mdl/context.rs
- wren-modeling-rs/core/src/mdl/dataset.rs
- wren-modeling-rs/core/src/mdl/lineage.rs
- wren-modeling-rs/core/src/mdl/manifest.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/core/src/mdl/utils.rs
- wren-modeling-rs/core/tests/data/mdl.json
As mentioned in https://github.com/Canner/wren-engine/pull/681#discussion_r1682494258, DataFusion moves many functions out of the core. If we used the context provider and created the expression by ourselves, we should register many functions for it. This PR uses `SessionCotnext#SessionState` to create what we need.
> Create expressions by SessionContext API

- ibis-server/README.md
- ibis-server/app/model/connector.py
- ibis-server/app/model/validator.py
- ibis-server/app/routers/v2/connector.py
- ibis-server/docs/development.md
- ibis-server/justfile
- close #691 
- I also enhanced the testing scripts in justfile and added some corresponding docs.
> Decouple the Rewriter and Connector in Ibis Server

- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/mdl/context.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/sqllogictest/src/engine/runner.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/sqllogictest/test_sql_files/view.slt
- wren-modeling-rs/wren-example/examples/to-many-calculation.rs
- Fix the `RemoveWrenPrefixRule` for the correct plan schema.
- Provide an API for applying rules for an existing session context.
- Make sqlloigctests tests to apply rules directly.
I didn't find the sqllogictests is broken. So, many test cases are failed and skipped but I didn't know. I commented out some cases and I'll file the issues for them.
> Fix `RemoveWrenPrefixRule` for being executed by DataFusion

- ibis-server/tests/routers/v2/test_analysis.py
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/Field.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/DecisionPointAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/ExprSource.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/ExpressionLocationAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalysis.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestDecisionPointAnalyzer.java
- wren-main/src/main/java/io/wren/main/web/AnalysisResource.java
- wren-main/src/main/java/io/wren/main/web/dto/QueryAnalysisDto.java
- wren-tests/src/test/java/io/wren/testing/TestAnalysisResource.java
close #683 
close #690 
The location of the join criteria is the most left-side expression. Because of the limitation of trino parser, we can't dedicate the precision location of the join type syntax (`ON` or `USING`). For example:
```
SELECT * FROM a JOIN b ON a.a1 = b.b1
```
The location of the criteria is the location of `a.a1`.
> Enhance the analysis API for the location of Join Criteria and source columns

- wren-modeling-rs/core/src/logical_plan/utils.rs
close #590 
- Ensure the type name is case-insensitive.
- Mapping the unknown type to `Utf8`
> Mapping WrenType to ArrowType

- ibis-server/app/model/metadata/factory.py
- ibis-server/app/model/metadata/trino.py
- ibis-server/tests/routers/v2/connector/test_trino.py
Created:
**(POST) /trino/metadata/tables API**
**Note:**
(POST) /trino/metadata/constraints API
_this API has not been developed because trino doesn't maintain primary key info._
Here is a reference : [StackOverflow-reference](https://stackoverflow.com/questions/74396666/how-do-you-define-a-primary-key-on-a-table-in-trino)
> feat: trino integration get tables name api developed

- ibis-server/tests/routers/v2/connector/test_mssql.py
The latest version of the MSSQL container will cause the timeout error for ibis CI. Fix the version to `2019-CU27-ubuntu-20.04` for stable testing.
> Fix MSSQL testcontainer to `2019-CU27-ubuntu-20.04` version

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestDecisionPointAnalyzer.java
We didn't build the correct scope for the CTE. This leads to some analysis errors when making the decision point analysis.
> Fix the scope analysis of the CTEs

- ibis-server/app/mdl/rewriter.py
Resolve https://github.com/Canner/WrenAI/issues/581
Ibis implements the MSSQL dialect for sqlglot. If we use sqlglot before using Ibis, the MSSQL dialect will not be registered in sqlglot. Therefore, we need to import the dialect from Ibis before using sqlglot.
> fix(mssql): import custom dialects from ibis library for sqlglot

- .github/workflows/ibis-ci.yml
Make CI use `justfile` instead original poetry command.
> chore(ci): setup just

- ibis-server/poetry.lock
- ibis-server/pyproject.toml
From fastapi [0.112.0](https://github.com/fastapi/fastapi/releases/tag/0.112.0), they removes the cli in the default package.
> fix(fastapi): edit dependency to include cli

- .github/workflows/ibis-ci.yml
- ibis-server/Dockerfile
- ibis-server/app/model/__init__.py
- ibis-server/app/model/data_source.py
- ibis-server/docs/development.md
- ibis-server/tests/routers/v2/connector/test_mssql.py
We found the `tdsodbc` version in the Debian 10 is 1.0 and may be too old not to support the `Azure SQL database`.
We will use `Microsoft ODBC 18 driver` instead of tdsodbc.
It will support SQL server version `2014` or later.
The msodbcsql driver 18.0 supports 2012, but the version is not on `ARM`.
We will use the latest MS ODBC 18 driver for arm64 and amd64. The latest version does not support 2012.
[Operating system support](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/system-requirements?view=sql-server-ver16#operating-system-support)
[SQL version compatibility](https://learn.microsoft.com/en-us/sql/connect/odbc/windows/system-requirements-installation-and-driver-files?view=sql-server-ver16#sql-version-compatibility)
> fix(mssql): use msodbcsql instead of tdsodbc

- ibis-server/app/util.py
- ibis-server/tests/routers/v2/connector/test_bigquery.py
- ibis-server/tests/routers/v2/connector/test_clickhouse.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
- ibis-server/tests/routers/v2/connector/test_mysql.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v2/connector/test_snowflake.py
- ibis-server/tests/routers/v2/connector/test_trino.py
If the data is null when the column type is a timestamp, data in the pandas dataframe will be a `NaT`(Not a Time) object. It could not be serialized to JSON in `orjson` ([issue](https://github.com/ijl/orjson/issues/249), [test case]( https://github.com/ijl/orjson/blob/master/test/test_numpy.py#L799)).
NaT is a type of `numpy`. The numpy provides a function [isnat](https://numpy.org/doc/stable/reference/generated/numpy.isnat.html) to determine it. But it will raise an error when the input is `pandas.NaT`. Fortunately, pandas provide a function [isnull](https://pandas.pydata.org/docs/reference/api/pandas.isnull.html) that could cover this type and also cover `NaN`.
> fix(ibis): determine the data is null or not

- ibis-server/tests/routers/test_ibis.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v3/connector/test_postgres.py
We don't need to assert the content. It will be asserted by the other module.
> chore(test): remove assert text content for dry_plan

- .github/workflows/integration-tests.yml
We make the PR from `dependabot` with the label `v1-engine-changed`, but the PR does not trigger ci `integration-test`.
The CI needs more activity types for the PR created with the label.
> ci(integration-tests): add more activity types

- ibis-server/tests/routers/v3/connector/test_postgres.py
- wren-modeling-py/src/lib.rs
- wren-modeling-py/tests/test_modeling_core.py
- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/analyze/relation_chain.rs
- wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
- wren-modeling-rs/core/src/logical_plan/utils.rs
- wren-modeling-rs/core/src/mdl/context.rs
- wren-modeling-rs/core/src/mdl/dataset.rs
- wren-modeling-rs/core/src/mdl/lineage.rs
- wren-modeling-rs/core/src/mdl/manifest.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/core/src/mdl/utils.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/sqllogictest/test_sql_files/model.slt
- wren-modeling-rs/sqllogictest/test_sql_files/view.slt
- wren-modeling-rs/wren-example/examples/datafusion-apply.rs
close #717 
After this changed, all name in the MDL will be case sensitive. Because the SQL text in the data fusion is lowercase by default, if the table or column name contains the uppercase, we should use it with quotes.
```rust
let manifest = ManifestBuilder::new()
.catalog("wrenai")
.schema("public")
.model(
ModelBuilder::new("Customer")
.table_reference("datafusion.public.customer")
.column(ColumnBuilder::new("custkey", "int").build())
.column(ColumnBuilder::new("name", "string").build())
.build(),
)
.build();
```
When query the model `Customer`, we should use the following SQL
```sql
SELECT * FROM wrenai.public."Customer"
```
However, the column `custkey` is all lowercase. We can just query it without qutoes:
```sql
SELECT custeky FROM wrenai.public."Customer"
```
> feat(core): support case sensitive identifier

- wren-modeling-rs/core/src/mdl/builder.rs
- wren-modeling-rs/core/src/mdl/manifest.rs
- wren-modeling-rs/core/tests/data/mdl.json
close #718 
Refer to [serde doc](https://serde.rs/container-attrs.html#rename_all), we use `SCREMING_SNAKE_CASE` and add alias for `snake_case`.
The Join type is supported serialized from both of the styles now.
```
one_to_one,  ONE_TO_ONE
```
> feat(core): handle JoinType serde using `SCREAMING_SNAKE_CASE` and `snake_case` style

- ibis-server/app/mdl/rewriter.py
We don't import this experiment lib when we do not use it.
> chore(wren-core): move the import in the function call

- ibis-server/app/model/__init__.py
- ibis-server/app/routers/v2/connector.py
- ibis-server/app/routers/v3/connector.py
- ibis-server/app/util.py
- ibis-server/tests/routers/v2/connector/test_bigquery.py
- ibis-server/tests/routers/v2/connector/test_clickhouse.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
- ibis-server/tests/routers/v2/connector/test_mysql.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v2/connector/test_snowflake.py
- ibis-server/tests/routers/v2/connector/test_trino.py
- ibis-server/tests/routers/v3/connector/test_postgres.py
We abandoned the unused feature `column_dtypes`.
If the dtype is datetime, we will format the data to string when building JSON.
> feat(ibis): adjust json data type and format

- ibis-server/tests/routers/v2/connector/test_clickhouse.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- wren-base/src/main/java/io/wren/base/sqlrewrite/WrenSqlRewrite.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDB.java
- Fix `count(*)` query with the filter that invokes any calculated field.
- Fix `count(*)` for a query with the relation `table` or `join`.
- Fix selecting wildcard from a model should exclude the calculated fields.
> fix(core): fix the behaviors of dynamic query

- ibis-server/app/custom_sqlglot/dialects/__init__.py
- ibis-server/app/custom_sqlglot/dialects/mysql.py
- ibis-server/app/mdl/rewriter.py
- ibis-server/app/util.py
- ibis-server/tests/routers/v2/connector/test_bigquery.py
- ibis-server/tests/routers/v2/connector/test_clickhouse.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
- ibis-server/tests/routers/v2/connector/test_mysql.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v2/connector/test_snowflake.py
- ibis-server/tests/routers/v2/connector/test_trino.py
- Handle bytes to hex string
- Override MySQL sqlglot dialect for fixing
- Remove unused table in the test
> fix(format): handle bytes to hex

- wren-modeling-rs/core/src/logical_plan/analyze/expand_view.rs
- wren-modeling-rs/core/src/logical_plan/analyze/mod.rs
- wren-modeling-rs/core/src/logical_plan/analyze/model_anlayze.rs
- wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
- wren-modeling-rs/core/src/logical_plan/utils.rs
- wren-modeling-rs/core/src/mdl/context.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- wren-modeling-rs/sqllogictest/test_files/model.slt
- wren-modeling-rs/sqllogictest/test_files/tpch/q22.slt.part
- Implement the query scope analysis to solve the subquery and correlated subquery syntax
- Fix the TPCH Q22 issue
- Refactor the ModelAnalyzeRule flow
> fix(core): implement the scope analysis to support the correlated subquery syntax

- docker/build-local.sh
- example/duckdb-tpch-example/etc/config.properties
- `wren-sqlglot-server` is a legacy module.
- `wren.experimental-enable-dynamic-fields` should be true by default now.
> chore(core): remove legacy command and config for example and script

- wren-modeling-py/Cargo.lock
- wren-modeling-py/Cargo.toml
- wren-modeling-py/pyproject.toml
- wren-modeling-rs/Cargo.toml
- wren-modeling-rs/core/Cargo.toml
- wren-modeling-rs/sqllogictest/Cargo.toml
- wren-modeling-rs/wren-example/Cargo.toml
- Remove the unnecessary feature from DataFusion dependency. Take expression-related features only. 
- Change the building profile to `release`
In my local environment, before removing them, the building time is
```
Finished release profile [optimized] target(s) in 8m 43s
```
After removing them, the time is
```
Finished release profile [optimized] target(s) in 7m 30s
```
> chore(core): remove unused dependency

- ibis-server/Dockerfile
Due to #798, the building for ibis-server image is always timeout. Remove the experimental feature for the stable building.
> chore(ibis): remove rust from ibis-server image

- ibis-server/Dockerfile
It seems the image building has been fine. Revert the changes to build with Rust.
close #798
> chore: revert remove rust from ibis-server image #804

- ibis-server/app/model/__init__.py
- ibis-server/app/model/data_source.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
Due to certain issues in previous versions of Ibis, we implemented workarounds. Now that Ibis has fixed these issues, let's remove these workarounds.
> chore(ibis): remove workaround since ibis update

- ibis-server/app/model/validator.py
- ibis-server/app/routers/v2/connector.py
- ibis-server/app/routers/v3/connector.py
- ibis-server/tests/routers/v2/connector/test_bigquery.py
- ibis-server/tests/routers/v2/connector/test_clickhouse.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
- ibis-server/tests/routers/v2/connector/test_mysql.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v2/connector/test_snowflake.py
- ibis-server/tests/routers/v2/connector/test_trino.py
- ibis-server/tests/routers/v2/test_relationship_valid.py
- ibis-server/tests/routers/v3/connector/test_postgres.py
- trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestDuckDBSqlConverter.java
This PR implements a new validation rule to validate if a relationship is valid. This validation is used to ensure the real data layout matches the definition. We have some rules for different relationship types. 
- ONE_TO_ONE
- The join column of the left table is unique.
- The join column of the right table is unique.
- The count of the join result is greater than 0.
- ONE_TO_MANY
- The join column of the left table is unique.
- The count of the join result is greater than 0.
- MANY_TO_ONE
- The join column of the right table is unique.
- The count of the join result is greater than 0.
- MANY_TO_MANY
- The count of the join result is greater than 0.
`relationship_is_valid`
```
POST /v2/connector/{data_source}/validate/relationship_is_valid
```
```
"connectionInfo": {......}, …
```
> feat(ibis): introduce the relationship validation 

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/Field.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/analyzer/TestStatementAnalyzer.java
The relationship column should be ignored when resolving the corresponding field. Otherwise, the resolved columns will always contain the relationship column.
Use `RelationType.resolveAnyField` to follow the same behavior.
> fix(core): fix the field resolving for the relationship column

- ibis-server/tests/routers/v3/connector/test_postgres.py
- wren-modeling-py/src/lib.rs
- wren-modeling-py/tests/test_modeling_core.py
- wren-modeling-rs/core/src/mdl/context.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/sqllogictest/src/test_context.rs
- After #819, we apply the optimization rule to simplify the generated SQL. However, DataFusion can't unparse the optimized plans well. Disable `optimize_projections` for a valid SQL result.
> fix(core): disable `optimize_projections` rule for SQL generation

- ibis-server/app/model/__init__.py
- ibis-server/app/model/data_source.py
We found an error.
```
('42000', '[42000] [FreeTDS][SQL Server]Unicode data in a Unicode-only collation or ntext data cannot be sent to clients using DB-Library (such as ISQL) or ODBC version 3.7 or earlier. (4004) (SQLFetch)')
```
The default TDS or ODBC version in the base image `python:3.11-slim-buster`(Debian 10) may be too low.
The default TDS version is `4.2`. Update the version, and it will be fine.
You can execute `tsql -C` in the container will get this.
```
Compile-time settings (established with the "configure" script)
Version: freetds v1.00.104
freetds.conf directory: /etc/freetds
MS db-lib source compatibility: no
Sybase binary compatibility: yes
Thread safety: yes
iconv library: yes
TDS version: 4.2
iODBC: no
unixodbc: yes
SSPI "trusted" logins: no
Kerberos: yes
OpenSSL: no …
```
> fix(mssql): update tds version

- wren-base/src/main/java/io/wren/base/dto/JoinType.java
- wren-tests/src/test/java/io/wren/testing/TestMDLResourceV2.java
Allow setting the Join type of relationship to `MANY_TO_MANY`.
> chore(core): allow to set MANY_TO_MANY relationship

- ibis-server/app/config.py
- ibis-server/app/mdl/rewriter.py
- ibis-server/app/routers/v2/connector.py
- ibis-server/tests/resource/functions.csv
- ibis-server/tests/routers/v3/connector/test_postgres.py
- ibis-server/tests/test_main.py
- wren-modeling-py/Cargo.lock
- wren-modeling-py/Cargo.toml
- wren-modeling-py/src/lib.rs
- wren-modeling-py/src/remote_functions.rs
- wren-modeling-py/tests/functions.csv
- wren-modeling-py/tests/test_modeling_core.py
- wren-modeling-rs/benchmarks/src/tpch/run.rs
- wren-modeling-rs/core/Cargo.toml
- wren-modeling-rs/core/src/mdl/function.rs
- wren-modeling-rs/core/src/mdl/mod.rs
- wren-modeling-rs/core/tests/data/functions.csv
- wren-modeling-rs/wren-example/Cargo.toml
- wren-modeling-rs/wren-example/examples/calculation-invoke-calculation.rs
- wren-modeling-rs/wren-example/examples/datafusion-apply.rs
- wren-modeling-rs/wren-example/examples/plan-sql.rs
- wren-modeling-rs/wren-example/examples/to-many-calculation.rs
- wren-modeling-rs/wren-example/examples/view.rs
When planning a SQL, DataFusion planner will strictly check the function usage. The used function should be registered in the SessionContext. In the Wren AI scenario, we always fully push down the SQL to the data source side. We can invoke the `ByPassFunction` (introduced by #802) which only requires the function name and return type to register a logical function for unparsing purposes.
This PR introduces a file-based register to define the required remote function easily.
The definition file is a CSV file that contains 4 columns and with the header:
- `function_type`: The possible value contains `scalar`, `aggregate`, and `window`. All of them are lowercase. 
- `name`: The function name.
- `return_type`: The expected return type.
- `description`: A simple description of this function. …
> feat(core): implement file-based remote function register

- .github/labeler.yml
- `any-glob-to-any-file`: ANY glob must match against ANY changed file
- `any-glob-to-all-files`: ANY glob must match against ALL changed files
- `all-globs-to-any-file`: ALL globs must match against ANY changed file
- `all-globs-to-all-files`: ALL globs must match against ALL changed files
Reference:
https://github.com/actions/labeler?tab=readme-ov-file#match-object
> ci(labeler): fix rule

- ibis-server/app/model/metadata/trino.py
- ibis-server/tests/routers/v2/connector/test_trino.py
> fix(trino): fix sql for querying metadata

- wren-modeling-rs/core/src/mdl/mod.rs
Try to infer the metadata of the source table from the manifest if the register tables aren't provided. 
There are some rules to infer the columns of the source table:
- If the column is calculated or has a relationship, it's not a source column.
-  If the column is without expression, it's a source column.
- If the column has an expression, it will try to infer the source column from the expression.
- If the expression is a simple column reference(`identifier` or `compound identifier`), it's the source column name.
- If the expression is complex, it can't be inferred. 
The source columns will be registered with the source table name in the session context.
> feat(core): infer the source column from the manifest

- ibis-server/tests/routers/v2/connector/test_bigquery.py
Due to the current date changing daily, the test can not exactly assert what is expected.
> test(bigquery): use fixed date instead of current date

- ibis-server/app/model/metadata/bigquery.py
- ibis-server/app/model/metadata/canner.py
- ibis-server/app/model/metadata/clickhouse.py
- ibis-server/app/model/metadata/metadata.py
- ibis-server/app/model/metadata/mssql.py
- ibis-server/app/model/metadata/mysql.py
- ibis-server/app/model/metadata/postgres.py
- ibis-server/app/model/metadata/trino.py
- ibis-server/app/routers/v2/connector.py
- ibis-server/tests/routers/v2/connector/test_bigquery.py
- ibis-server/tests/routers/v2/connector/test_canner.py
- ibis-server/tests/routers/v2/connector/test_clickhouse.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
- ibis-server/tests/routers/v2/connector/test_mysql.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v2/connector/test_snowflake.py
- ibis-server/tests/routers/v2/connector/test_trino.py
Add new API `/v2/connector/{data_source}/metadata/version` to provide the DB version.
The request body follows other metadata APIs.
> feat(metadata): provide db version

- wren-core-py/Cargo.lock
solve https://github.com/Canner/wren-engine/security/dependabot/55
> chore(core-py-deps): bump lexical-core from 0.8 to 1.0 and update the lock in /wren-core-py groups

- ibis-server/app/mdl/rewriter.py
- ibis-server/app/routers/v3/connector.py
- ibis-server/tests/routers/v3/connector/test_postgres.py
- wren-core-py/Cargo.lock
- wren-core-py/Cargo.toml
- wren-core-py/src/context.rs
- wren-core-py/src/errors.rs
- wren-core-py/src/lib.rs
- wren-core-py/src/remote_functions.rs
- wren-core-py/tests/functions.csv
- wren-core-py/tests/test_modeling_core.py
- wren-core/core/src/lib.rs
- wren-core/core/src/mdl/function.rs
- wren-core/core/src/mdl/mod.rs
- wren-core/core/tests/data/functions.csv
Introduce the PySessionContext to handle the status of different sessions. The session context contains an analyzed MDL and the required available function list.
- Move the `transfromed_sql` and `read_remote_functions` to the PySessionContext.
- Provide the API for the available function list
```
GET /v3/connector/functions
```
> feat(core): introduce `PySessionContext` and the API for the available function list

- ibis-server/poetry.lock
- ibis-server/pyproject.toml
We use `gql` in the regular codebase. But it is mistakenly put into the dev group.
> fix(deps): gql is in wrong group

- .github/workflows/build-dev-image.yml
- .github/workflows/build-image.yml
- .github/workflows/stable-release.yml
Use the gha cache to reduce building time. I wish it worked.
Reference:
https://docs.docker.com/build/cache/backends/gha/
> ci(docker): use gha cache

- ibis-server/tests/routers/v3/connector/test_postgres.py
- wren-core-py/src/context.rs
- wren-core-py/src/errors.rs
- wren-core/core/src/mdl/builder.rs
- wren-core/core/src/mdl/manifest.rs
`properties` is never used on the engine side. We can remove it, and then the Wren AI side can use it more flexibly.
> feat(core): remove properties field from mdl and improve the error message

- ibis-server/pyproject.toml
- ibis-server/tools/README.md
- ibis-server/tools/mdl_validation.py
Introduce a Python script to validate if a Wren MDL is valid locally.
> chore(ibis): implement mdl validation scripts

- .github/workflows/ibis-ci.yml
- wren-core/core/src/mdl/builder.rs
- wren-core/core/src/mdl/dataset.rs
- wren-core/core/src/mdl/lineage.rs
- wren-core/core/src/mdl/manifest.rs
- wren-core/core/src/mdl/mod.rs
This PR introduces a new column property, `is_hidden`. A hidden column means this column is defined in the MDL but it can't be used in the query.
The main purpose of a hidden column is to infer the remote source column. Sometimes, we want to apply something on a remote column like, casting, lowercase, or trim. we may write the MDL like
```json
{
"name": "date_in_int_col",
"type": "date",
"expression": "cast(date_in_int_col as date)"
}
```
However, according to the rule of https://github.com/Canner/wren-engine/pull/844, we can get a remote column from a casting expression. So `date_in_int_col` won't be registered as a source column, the column expression isn't valid.
In this case, we should add another column for the column inferring but we don't want to expose this column. So we can …
> feat(core): introduce the hidden column

- .github/workflows/build-dev-image.yml
- .github/workflows/build-image.yml
- .github/workflows/stable-release.yml
This reverts commit 282c953b103eccad32055612ba526964f62aada5.
We found the docker cache will cause `System.IO.IOException: No space left on device`.
https://github.com/Canner/wren-engine/actions/runs/11574176406
Unexpectedly, we've filled up our entire GitHub cache, reaching the 10GB limit.
> revert(docker): not use gha cache

- ibis-server/tools/README.md
- ibis-server/tools/query_local_run.py
This PR implements a simple Python script to execute an SQL locally. Currently, only implement the BigQuery connection in this PR.
Given the required environment variables, we can input an SQL file like
```
poetry run python tools/query_local_run.py < test.sql
```
> chore(ibis): introduce a script for query locally

- .github/workflows/ibis-ci.yml
- ibis-server/Dockerfile
- ibis-server/app/model/__init__.py
- ibis-server/docs/development.md
- ibis-server/tests/routers/v2/connector/test_mssql.py
This reverts commit 082a8071e8f01b4c41a9ee2a5a539c3232ebfe2f.
Resolve #763
> feat(mssql): use msodbcsql instead of freetds

- ibis-server/app/model/metadata/dto.py
Pydantic performs a check on all subclasses of BaseModel to identify any overlapping field names with the base BaseModel class. It then generates a warning to discourage the use of identical field names to mitigate shadowing issues.
```
.venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:172
.../wren-engine/ibis-server/.venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:172: UserWarning: Field name "schema" in "TableProperties" shadows an attribute in parent "BaseModel"
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> chore(metadata): avoid using schema as a field name

- .github/workflows/ibis-ci.yml
Sometimes, we update the Rust code, but other existing PRs do not update the Rust core. This may be because of the cache.
> ci(ibis): update core to avoid caching

- .github/workflows/ibis-ci.yml
By introducing a delay after the Trino container startup, we resolved the issue https://github.com/Canner/wren-engine/issues/671.
So we can reintegrate Trino tests into the standard tests.
> ci(ibis): append Trino test to standard tests

- .github/workflows/build-dev-image.yml
- .github/workflows/build-image.yml
- .github/workflows/maven-tests.yml
- .github/workflows/stable-release.yml
We found if the job only builds one platform, it takes 16 minutes. So we can split the two platforms building into two jobs and let them be parallel to reduce the building time.
And also upgrade the `setup-java` action version to avoid warnings.
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> ci(image): split ibis building to two jobs

- wren-core/core/src/mdl/context.rs
- wren-core/core/src/mdl/mod.rs
Close #876 
DataFusion `CountWildcardRule` will try to rewrite `Count(Expr:Wildcard)` to `Count(Expr:Literal)`. It will generate an alias name `count(*)` which isn't allowed by BigQuery. Disable this rule for BigQuery.
> fix(core): disable `CountWildcardRule` for BigQuery source

- ibis-server/app/model/data_source.py
- ibis-server/tests/routers/v2/connector/test_mssql.py
We found the error 
```
'IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)'
```
Because the password of mssql includes special characters like `{R;3G1/8Al2AniRye` that start with `{` or include `;`.
It should be covered by `{` and `}` and replace `}` with`}}`.
Reference:
https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-databases
https://stackoverflow.com/questions/78531086/pyodbc-connection-string-correctly-escaping-password-with-special-characters/78532507#78532507
> fix(mssql): escape special characters for odbc

- ibis-server/tests/routers/v3/connector/bigquery/test_query.py
- wren-core/core/src/logical_plan/mod.rs
- wren-core/core/src/logical_plan/optimize/mod.rs
- wren-core/core/src/logical_plan/optimize/simplify_timestamp.rs
- wren-core/core/src/mdl/context.rs
- wren-core/core/src/mdl/mod.rs
We will simplify the timestamp literal when planning SQL to support the complex timezone issues in the different data sources. Something like
- MSSQL only accepts the time zone offset.
- Clikchouse only accepts the name of the time zone.
- BigQuery has timestamp (impacted by timezone) and Datetime (non-impacted by timezone).
To handle them, Wren Core will convert all of the time zone literals to UTC, which is how other databases process the timestamp with the time zone literal.
Powered by DataFusion, both the offset and the timezone name are allowed. It can also handle the DST issue.
When you input a SQL like
```
select timestamp '2011-01-01 18:00:00 Asia/Taipei'
```
The planned SQL will be
```
SELECT CAST('2011-01-01 10:00:00' AS TIMESTAMP)
```
Then, the dialect will be if the dialect is …
> feat(core): introduce Timestamp Simplify rule to handle timezone

- ibis-server/resources/function_list/bigquery.csv
- ibis-server/tests/routers/v3/connector/bigquery/conftest.py
- ibis-server/tests/routers/v3/connector/bigquery/test_functions.py
- ibis-server/tests/routers/v3/connector/bigquery/test_query.py
The redundant comma causes the function can't be registered. I also added tests to assert if it's available.
> fix(ibis): remove redundant comma of the function list

- .github/workflows/build-image.yml
We found the sha tag missing. Because we cover the text by `>` when writing to the `tags.txt`, it should be `>>` to append it.
I also found an entry `type=schedule` that can delegate `nightly`. 
https://github.com/docker/metadata-action?tab=readme-ov-file#typeschedule
> ci(image): fix missing sha tag

- ibis-server/app/model/metadata/factory.py
- ibis-server/app/model/metadata/snowflake.py
- ibis-server/tests/routers/v2/connector/test_snowflake.py
- ibis-server/tests/routers/v3/connector/snowflake/test_functions.py
Implement Snowflake Metadata APIs [#709](https://github.com/Canner/WrenAI/issues/709)
```json
{
"user": "my-user",
"password": "my-pwd",
"account": "my-account",
"database": "my-db",
"schema": "my-schema"
}
}
```
- name: unique table name
- columns
- name: column name in the datasource
- type: column data type
- notNull: boolean, nullable or not
- description: column description(comment) if any
- properties: column properties if any
- description: table description if any 
- properties
- schema: schema name to build tableReference
- catalog: catalog name to build tableReference
- table: table name to build tableReference
- primaryKey: the column name which is bind with primary constraint    
```json
[
{
"name": "db.REGION",
"columns": [
{
"name": "R_COMMENT",
"type": …
```
> feat(ibis): Implement Snowflake Metadata APIs

- wren-core/core/src/mdl/context.rs
- wren-core/core/src/mdl/mod.rs
Sometimes, we will cast a timestamp column to a timestamp type because we must handle the `DATETIME` and `TIMESTAMP` for the BigQuery. However, `push_down_filter` will remove the casting because it can't differentiate `DATETIME` and `TIMESTAMP` in the DataFusion layer.
see the unit test for the details.
If applying `push_down_filter`, the result will be as below. However, it will fail if `出道時間` is `DATETIME` in BigQuery
```sql
SELECT 
count(*) 
FROM 
(
SELECT 
artist.cast_timestamp 
FROM 
(
SELECT 
CAST(
artist."出道時間" AS TIMESTAMP WITH TIME ZONE
) AS cast_timestamp 
FROM 
artist 
WHERE 
artist."出道時間" > CAST(
'2011-01-01 21:00:00' AS TIMESTAMP
)
) AS artist
) AS artist
```
> fix(core): disable pushdown filter to keep the casting for timestamp column

- ibis-server/app/mdl/context.py
- ibis-server/docs/development.md
Allow the core to remain uninstalled when not using the v3 API.
> chore(ibis): move the wren_core into function

- wren-core-py/src/context.rs
- wren-core/core/src/logical_plan/analyze/plan.rs
- wren-core/core/src/logical_plan/utils.rs
- wren-core/core/src/mdl/dataset.rs
- wren-core/core/src/mdl/dialect.rs
- wren-core/core/src/mdl/mod.rs
- close #906 
- Support to define array and struct type in the MDL.
- Array: `array<int>`
- Struct: `struct<number int, name varchar>`
- Support to unparse array and struct to the SQL
The array of struct isn't supported now. 
- `array<struct<number int>`
> feat(core): support to Array and Struct type

- wren-core/core/src/mdl/context.rs
- wren-core/core/src/mdl/mod.rs
`CommonSubexprEliminate` is used to clean up the duplicate expressions. However, it could generate a plan like
```
Projection: c.properties_first AS contact_first_name, c.properties_last AS contact_last_name, c.properties_e AS properties_e_a
Projection: c.createdAt, c.properties_e, c.properties_first, c.properties_last
Filter: __common_expr_1 >= CAST(CAST(Utf8("2024-11-01 00:00:00") AS Timestamp(Nanosecond, None)) AS Timestamp(Nanosecond, Some("+00:00"))) AND __common_expr_1 < CAST(CAST(Utf8("2024-11-15 00:00:00") AS Timestamp(Nanosecond, None)) AS Timestamp(Nanosecond, Some("+00:00")))
Projection: CAST(c.createdAt AS Timestamp(Nanosecond, Some("+00:00"))) AS __common_expr_1, c.createdAt, c.properties_e, c.properties_first, c.properties_last
```
This plan has continued projection plans …
> fix(core): disable CommonSubexprEliminate to avoid generate invalid plan for unparsing

- .github/workflows/build-image.yml
- .github/workflows/stable-release.yml
We found the tag `nightly` is missing and the step in stable release will fail because the command format is wrong.
> ci(image): fix missing nightly tag and fix tag when building imagetools

- .github/workflows/maven-tests.yml
If the PR already has other tags, the condition `github.event.label.name == 'v1-engine-changed'` is false.
We need to use `contains` instead of it.
> ci(maven-test): fix condition

- ibis-server/app/mdl/analyzer.py
- ibis-server/app/mdl/rewriter.py
- ibis-server/app/middleware/__init__.py
- ibis-server/docs/development.md
Use `Java Engine` to distinguish between ibis-server and java-server.
> chore: adjust wording and log

- wren-base/src/main/java/io/wren/base/WrenMDL.java
- wren-base/src/main/java/io/wren/base/dto/Column.java
- wren-base/src/main/java/io/wren/base/dto/CumulativeMetric.java
- wren-base/src/main/java/io/wren/base/dto/DateSpine.java
- wren-base/src/main/java/io/wren/base/dto/EnumDefinition.java
- wren-base/src/main/java/io/wren/base/dto/EnumValue.java
- wren-base/src/main/java/io/wren/base/dto/Macro.java
- wren-base/src/main/java/io/wren/base/dto/Measure.java
- wren-base/src/main/java/io/wren/base/dto/Metric.java
- wren-base/src/main/java/io/wren/base/dto/Model.java
- wren-base/src/main/java/io/wren/base/dto/Relationship.java
- wren-base/src/main/java/io/wren/base/dto/View.java
- wren-base/src/main/java/io/wren/base/dto/Window.java
- wren-base/src/test/java/io/wren/base/dto/TestManifestSerDe.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/AbstractTestFramework.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/AbstractTestModel.java
- wren-base/src/test/java/io/wren/base/sqlrewrite/TestCumulativeMetric.java
- wren-tests/src/test/resources/duckdb/mdl.json
- wren-tests/src/test/resources/tpch_mdl.json
Remove the unused `properties` field from the MDL, Then, the user can apply the structure they want.
```json
"properties": {
"field": "test1",
"nested": {
"n1": "test1",
"n2": "test2"
}
}
```
> chore(core): remove unused `properties` field

- wren-core/core/src/mdl/function.rs
> fix(core): make aggregate functions and window functions support zero argument

- .github/labeler.yml
Before we split the tests of Trino, we need to append the label `trino` to trigger CI.
Now we integrate the tests so we don't need this label.
> ci(labeler): remove unused label

- ibis-server/app/model/metadata/snowflake.py
This PR resolves the issue where Snowflake foreign key relationships were not displayed during setup phase by removing the `memtable` function.
- Snowflake tables with foreign keys defined:
- Snowflake tables without foreign keys:
Fix #940
> fix(ibis): Display Snowflake constraints without memtable

- ibis-server/tests/conftest.py
- ibis-server/tests/routers/v3/connector/bigquery/test_functions.py
- ibis-server/tests/routers/v3/connector/postgres/test_functions.py
- ibis-server/tests/routers/v3/connector/snowflake/test_functions.py
- wren-core-py/Cargo.lock
- wren-core-py/tests/test_modeling_core.py
- wren-core/Cargo.toml
- wren-core/core/src/mdl/dialect.rs
- wren-core/core/src/mdl/function.rs
- wren-core/core/src/mdl/mod.rs
- wren-core/sqllogictest/test_files/tpch/q7.slt.part
- wren-core/sqllogictest/test_files/tpch/q8.slt.part
- wren-core/sqllogictest/test_files/tpch/q9.slt.part
- To support the syntax of the array of structs like `a[1].b.c`, I enhanced the `sqlparser-rs` syntax
- https://github.com/apache/datafusion-sqlparser-rs/pull/1541
- Implement the planner behavior on the DataFusion side
- https://github.com/goldmedal/datafusion/pull/1
Before they are merged back into the DataFusion, Wren core will be based on the specific commit to support the syntax.
> feat(core): upgrade DataFusion to support the array of struct syntax

- wren-core/core/src/mdl/dialect.rs
- wren-core/core/src/mdl/mod.rs
Part of #930 
Refer to [the interval style of DataFusion](https://github.com/apache/datafusion/blob/172e5573270ae4a3d152d5bf15c5c0008595090e/datafusion/sql/src/unparser/dialect.rs#L171), `MySQL` style is more common for various data sources.
> feat(core): use MySQL interval style for output format

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/Scope.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/decisionpoint/RelationAnalyzer.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDBTableFunction.java
We're missing to analyze the expression in the `UNNEST` and `LATERAL`. It may cause the wrong model generation. The following SQL would be failed:
- `select u.a1 from nested_table n, unnest(n.a1) u(a1)`
- `select l.a1 from nested_table n cross join lateral (select n.a1[1]) l(a1)`
> fix(core): fix the StatementAnalyzer for UNNEST and LATERAL query

- wren-main/src/main/java/io/wren/main/PreviewService.java
- wren-main/src/main/java/io/wren/main/web/SystemResource.java
- wren-server/src/main/java/io/wren/server/WrenServer.java
- wren-server/src/main/java/io/wren/server/module/WebModule.java
We noticed that the first request to the Java engine is often timed out.
The Ibis server calls the Java engine timeout `5s`.
So we warm up the Java engine when it starts.
The warm-up time: ~5s. The warm-up case can not be too simple like `SELECT 1`. It will be ineffective.
Docker resource limit
```yaml
java-engine:
deploy:
resources:
limits:
cpus: '0.5'
memory: 2G
```
API: `POST {{ibis-server}}/v2/connector/dry-plan`
- Before: timeout(over 5s)
- After: 1.52s, 1.65s, 1.79s, 1.92s
[Java warm up](https://www.baeldung.com/java-jvm-warmup)
[python httpx timeouts](https://www.python-httpx.org/advanced/timeouts)
[docker compose resource](https://docs.docker.com/reference/compose-file/deploy/#resources)
> feat(java): warm up java engine

- wren-core/core/src/mdl/context.rs
- wren-core/core/src/mdl/mod.rs
Given a SQL using distinct aggregation
```sql
SELECT c_custkey, count(distinct c_name) FROM customer GROUP BY c_custkey
```
It will be planned to multiple aggregation plans by `SingleDistinctToGroupBy ` like
```
Projection: customer.c_custkey, count(DISTINCT customer.c_name)
Projection: customer.c_custkey, count(alias1) AS count(DISTINCT customer.c_name)
Aggregate: groupBy=[[customer.c_custkey]], aggr=[[count(alias1)]]
Aggregate: groupBy=[[customer.c_custkey, customer.c_name AS alias1]], aggr=[[]]
SubqueryAlias: customer
Projection: customer.c_custkey, customer.c_name
SubqueryAlias: customer
Projection: customer.c_custkey AS c_custkey, customer.c_name AS c_name
TableScan: customer
```
However, The unparser can't process it well. Disable it to get the simpler plan:
```
Projection: …
```
> fix(core): disable `SingleDistinctToGroupBy` for distinct aggregation unparsing

- ibis-server/app/main.py
- ibis-server/app/mdl/java_engine.py
- ibis-server/app/routers/v2/connector.py
Should make the resource depend on FastAPI.
Follow this tips
https://github.com/kludex/fastapi-tips?tab=readme-ov-file#6-use-lifespan-state-instead-of-appstate
https://github.com/kludex/fastapi-tips?tab=readme-ov-file#9-your-dependencies-may-be-running-on-threads
He is a maintainer of [Uvicorn](https://github.com/encode/uvicorn) and [Starlette](https://github.com/encode/starlette), and  also considered a [FastAPI Expert](https://fastapi.tiangolo.com/fastapi-people/#experts).
> chore: use lifespan and depends

- wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
- wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDB.java
Because the scope analysis isn't fully finished in the Java engine, the check for the union schema is wrong. The Java engine's main purpose is to be a pure SQL planner. We don't need to do too many checks. Just focus on collecting which columns and models are required.
This PR removes the checks for the union's input to ensure the union works well.
> fix(core): remove unused check to fix union syntax

- .github/workflows/stable-release.yml
Auto-generate gh release note when stable-releasing
Ref: https://github.com/softprops/action-gh-release
> ci(release): auto generate gh release note

- .github/workflows/stable-release.yml
Follow https://github.com/Canner/wren-engine/pull/994
We mistakenly remove the tag.
The `action-gh-release` does not create a tag. We need to generate a tag by ourselves.
> ci(release): fix missing tag

- .github/workflows/stable-release.yml
Because `maven release:prepare` will create a new version tag. So we don't need to make the tag ourselves.
> ci(release): remove unused job for push-tag

- ibis-server/tests/test_main.py
Use the same one client to avoid unnecessary lifespan trigger.
> test: make test use fixture

- ibis-server/app/main.py
- ibis-server/app/mdl/java_engine.py
- ibis-server/app/pattern/__init__.py
Add class `State` for lifespan and use state of lifespan instead of Singleton and remove unused `get_java_engine_connector` function
> chore: add class State and use state instead of singleton

- ibis-server/app/mdl/rewriter.py
- ibis-server/tests/routers/v2/connector/test_postgres.py
- ibis-server/tests/routers/v3/connector/postgres/test_dry_plan.py
- ibis-server/tests/routers/v3/connector/postgres/test_query.py
Resolve #1004
In v2, log the error and use the original manifest when it failed
However, in v3, the error is still raised.
> feat(extract): handle extraction failed

- .github/workflows/build-image.yml
Fix the typo in the action flow.
Has been tested:
https://github.com/Canner/wren-engine/actions/runs/12479200940
> fix: fix the context typo for build-image flow

- wren-core-base/manifest-macro/src/lib.rs
- wren-core-base/src/mdl/builder.rs
- wren-core-base/src/mdl/cls.rs
- wren-core-base/src/mdl/manifest.rs
- wren-core-base/src/mdl/mod.rs
- wren-core-base/tests/data/mdl.json
Introduce the `RowLevelSecurity` and `ColumnLevelSecurity` for MDL.
Now, we can define a column in the MDL JSON like
```json
{
"name": "rls_orderkey",
"type": "integer",
"expression": "o_orderkey",
"rls": {
"name": "SESSION_STATUS",
"operator": "EQUALS"
}
},
{
"name": "cls_orderkey",
"type": "integer",
"expression": "o_orderkey",
"cls": {
"name": "SESSION_LEVEL",
"operator": "EQUALS",
"threshold": "'NORMAL'"
}
}
```
- Implement the functionality of the data control in the planner.
> feat(core): introduce data control attributes for wren MDL base

- ibis-server/poetry.lock
- ibis-server/tests/conftest.py
- ibis-server/tests/routers/v3/connector/postgres/test_functions.py
- wren-core-py/Cargo.lock
- wren-core-py/poetry.lock
- wren-core-py/tests/test_modeling_core.py
- wren-core/Cargo.toml
- wren-core/core/src/logical_plan/analyze/plan.rs
- wren-core/core/src/mdl/dialect/utils.rs
- wren-core/core/src/mdl/dialect/wren_dialect.rs
- wren-core/core/src/mdl/function.rs
- wren-core/core/src/mdl/mod.rs
- Sync from https://github.com/goldmedal/datafusion/pull/2
- This branch supports the nested type access chain like `struct_col.f1.f2[1].f3`
> feat(core): sync DataFusion for the latest SQL syntax

- ibis-server/README.md
- ibis-server/app/routers/v2/analysis.py
- ibis-server/app/routers/v2/connector.py
- ibis-server/app/routers/v3/connector.py
- ibis-server/tests/routers/v3/connector/postgres/test_fallback_v2.py
- ibis-server/tests/routers/v3/connector/postgres/test_model_substitute.py
- ibis-server/tests/routers/v3/connector/postgres/test_query.py
- Wren AI is migrating to v3 API. However, the engine side keeps a fallback mechanism for backward supporting the legacy SQL syntax. 
- We also log the event to the stdout and encourage the user to report the error.
> chore(ibis): add the fallback mechanism for v3 API

- README.md
Upload the demo video and update README
> chore(mcp): add mcp demo mp4
