accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/MetricSqlRender.java
accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/ModelSqlRender.java
accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/RelationableSqlRender.java
accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/analyzer/StatementAnalyzer.java
accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestCumulativeMetric.java
accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestMetric.java

- Support metric on metric / cumulative metric
`cumulative metric` on `metric`/`cumulative metric` will be introduced in next pr.

Support `metric` on `metric`/`cumulative metric`

---

.github/workflows/deploy.yml

the proof that confirm this pr works fine.
https://github.com/brandboat/accio/actions/runs/6939846782
https://github.com/brandboat/accio/actions/runs/6939843202
both of them are failed since I didn't setup aws credential in my fork thus can't upload to s3 maven repo.

Trigger deploy by tag

---

accio-cache/src/main/java/io/accio/cache/CacheManager.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestCache.java
accio-tests/src/test/resources/cache/cache_mdl.json

We should also remove the task from the task list after clearing the data and canceling the task.

Remove the cache task from task list when removing cache

---

.github/workflows/build-dev-image.yml

use docker buildx to build multi arch image, will build upon every commit push to main branch, and add image tags `main-{short_last_commit_sha}` and `latest`.

Build multi arch image on main commit push

---

.gitignore

avoid misuploading http-request.log or other logs under var directory

Ignore all var directories

---

accio-base/src/main/java/io/accio/base/AccioMDL.java
accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/AccioDataLineage.java
accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/AccioSqlRewrite.java
accio-sqlrewrite/src/main/java/io/accio/sqlrewrite/analyzer/StatementAnalyzer.java
accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestAccioDataLineage.java
accio-sqlrewrite/src/test/java/io/accio/sqlrewrite/TestCumulativeMetric.java

note that even enable dynamic fields, every field in cumulative metric are still evolved since cumulative metric is a static sql pattern, and itself couldn't be dynamic.

Take care cumulative metric in enable dynamic fields mode

---

accio-base/src/main/java/io/accio/base/AnalyzedMDL.java
accio-base/src/main/java/io/accio/base/sqlrewrite/AccioPlanner.java
accio-base/src/main/java/io/accio/base/sqlrewrite/AccioRule.java
accio-base/src/main/java/io/accio/base/sqlrewrite/AccioSqlRewrite.java
accio-base/src/main/java/io/accio/base/sqlrewrite/EnumRewrite.java
accio-base/src/main/java/io/accio/base/sqlrewrite/MetricRollupRewrite.java
accio-base/src/main/java/io/accio/base/sqlrewrite/QueryDescriptor.java
accio-base/src/main/java/io/accio/base/sqlrewrite/ViewInfo.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestAllRulesRewrite.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestCumulativeMetric.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestEnumRewrite.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetricViewSqlRewrite.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestModel.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestModelSqlRewrite.java
accio-cache/src/main/java/io/accio/cache/CacheManager.java
accio-main/src/main/java/io/accio/main/AccioManager.java
accio-main/src/main/java/io/accio/main/AccioMetastore.java
accio-main/src/main/java/io/accio/main/PreviewService.java
accio-main/src/main/java/io/accio/main/pgcatalog/builder/PgCatalogTableBuilder.java
accio-main/src/main/java/io/accio/main/web/LineageResource.java
accio-main/src/main/java/io/accio/main/web/MDLResource.java
accio-main/src/main/java/io/accio/main/wireprotocol/WireProtocolSession.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestCache.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestDuckdbRetryCacheTask.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestDuckdbTaskManager.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestRefreshCache.java

pass AnalyzedMDL to AccioSqlRewrite to avoid run data lineage in every sql.

Pass AnalyzedMDL to sqlrewrite

---

accio-base/src/main/java/io/accio/base/AccioMDL.java
accio-base/src/main/java/io/accio/base/dto/Column.java
accio-base/src/main/java/io/accio/base/dto/CumulativeMetric.java
accio-base/src/main/java/io/accio/base/dto/DateSpine.java
accio-base/src/main/java/io/accio/base/dto/EnumDefinition.java
accio-base/src/main/java/io/accio/base/dto/EnumValue.java
accio-base/src/main/java/io/accio/base/dto/Macro.java
accio-base/src/main/java/io/accio/base/dto/Manifest.java
accio-base/src/main/java/io/accio/base/dto/Measure.java
accio-base/src/main/java/io/accio/base/dto/Metric.java
accio-base/src/main/java/io/accio/base/dto/Model.java
accio-base/src/main/java/io/accio/base/dto/Relationship.java
accio-base/src/main/java/io/accio/base/dto/TimeGrain.java
accio-base/src/main/java/io/accio/base/dto/View.java
accio-base/src/main/java/io/accio/base/dto/Window.java
accio-base/src/test/java/io/accio/base/dto/TestMacro.java
accio-base/src/test/java/io/accio/base/dto/TestManifestSerDe.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestCumulativeMetric.java

also mark description `@Deprecated`

Add properties to all DTOs and use toStringHelper

---

accio-base/src/main/java/io/accio/base/dto/Column.java
accio-base/src/main/java/io/accio/base/sqlrewrite/Utils.java
accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/ExpressionTypeAnalyzer.java
accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/Field.java
accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestExpressionTypeAnalyzer.java
accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestStatementAnalyzer.java
accio-tests/src/test/java/io/accio/testing/TestAnalysisResource.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestWireProtocolWithBigquery.java
accio-tests/src/test/resources/bigquery/TestWireProtocolWithBigquery.json

Fix the query scope analysis for the WITH query. The wrong analysis will make the type analysis and type coercion be wrong.

Fix the scope analyzer for with query statement

---

accio-base/src/main/java/io/accio/base/sqlrewrite/analyzer/StatementAnalyzer.java
accio-base/src/test/java/io/accio/base/sqlrewrite/TestMetric.java
accio-base/src/test/java/io/accio/base/sqlrewrite/analyzer/TestStatementAnalyzer.java

We missed to collect the columns when analyze where statement.

Fix collect required fields in where statement in dynamic calculated mode

---

accio-base/src/main/java/io/accio/base/client/duckdb/DuckDBDataSource.java
accio-main/src/main/java/io/accio/main/pgcatalog/PgCatalogManager.java
accio-tests/src/test/java/io/accio/testing/bigquery/TestResultSetMetadata.java
pom.xml

DuckDB has releases the new stable version. Let's upgrade our version to the stabel version.

Upgrade DuckDB to 0.10.0

---

accio-base/src/main/java/io/accio/base/client/duckdb/DuckdbUtil.java
accio-main/src/main/java/io/accio/main/wireprotocol/patterns/MetabaseTablePrivilegesLegacy.java
accio-main/src/main/java/io/accio/main/wireprotocol/patterns/MetabaseTablePrivilegesV0486.java
accio-main/src/main/java/io/accio/main/wireprotocol/patterns/PostgreSqlRewriteUtil.java
accio-main/src/test/java/io/accio/main/wireprotocol/TestPostgreSqlRewriteUtil.java

Metabase v0.48.6 release changes the table privilege SQL. We need to support the latest pattern.

Support Metabase v0.48.6

---

accio-base/src/main/java/io/accio/base/AccioMDL.java
accio-base/src/main/java/io/accio/base/Utils.java
accio-base/src/main/java/io/accio/base/dto/Column.java
accio-base/src/main/java/io/accio/base/dto/CumulativeMetric.java
accio-base/src/main/java/io/accio/base/dto/DateSpine.java
accio-base/src/main/java/io/accio/base/dto/EnumDefinition.java
accio-base/src/main/java/io/accio/base/dto/EnumValue.java
accio-base/src/main/java/io/accio/base/dto/Macro.java
accio-base/src/main/java/io/accio/base/dto/Manifest.java
accio-base/src/main/java/io/accio/base/dto/Measure.java
accio-base/src/main/java/io/accio/base/dto/Metric.java
accio-base/src/main/java/io/accio/base/dto/Model.java
accio-base/src/main/java/io/accio/base/dto/Relationship.java
accio-base/src/main/java/io/accio/base/dto/TimeGrain.java
accio-base/src/main/java/io/accio/base/dto/View.java
accio-base/src/main/java/io/accio/base/dto/Window.java
accio-base/src/main/java/io/accio/base/sqlrewrite/Utils.java
accio-base/src/test/java/io/accio/base/dto/TestManifestSerDe.java

- Add empty string check for required field.
- We only roughy test empty string for some common fileds.
- Print the expression when parsing failed.

Enhance the error handling for creating MDL

---

example/.env
example/README.md
example/docker-compose.yaml
example/etc/accounts
example/etc/config.properties
example/etc/mdl/sample.json

Provide an example for docker-compose usgae

---

accio-base/src/main/java/io/accio/base/config/ConfigManager.java
accio-base/src/main/java/io/accio/base/config/PostgresConfig.java
accio-tests/src/test/java/io/accio/testing/duckdb/AbstractWireProtocolTestWithDuckDB.java
accio-tests/src/test/java/io/accio/testing/duckdb/TestDeployDuckDBRuntime.java

Add TestDeployDuckDBRuntime
Fix typo

Add TestDeployDuckDBRuntime

---

README.md
example/README.md

- Remove all description.
- Keep the methods for building and running the server.
- Refine the readme of example

Refine the readme 

---

wren-main/src/main/java/io/wren/main/sql/bigquery/RemoveColumnAliasInAliasRelation.java
wren-main/src/main/java/io/wren/main/sql/duckdb/RewriteFunction.java
wren-main/src/main/java/io/wren/main/wireprotocol/Messages.java
wren-tests/src/main/java/io/wren/testing/TestingWireProtocolClient.java
wren-tests/src/test/java/io/wren/testing/TestMetadataQuery.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestBigQuerySqlConverter.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolWithBigquery.java
wren-tests/src/test/java/io/wren/testing/duckdb/TestWireProtocolWithDuckDB.java
wren-tests/src/test/java/io/wren/testing/postgres/TestWireProtocolWithPostgres.java

- Fix RemoveColumAliasInAliasRelation for BigQuery connector.
- Fix Function name as a deference expression for DuckDB SqlConverter

Fix Rewrite Rule for Metabase connection

---

wren-tests/src/test/java/io/wren/testing/duckdb/TestStartWithDuckDB.java

Using ImmutableMap could cause duplicate entry errors in the concurrent testing.

Modify to avoid duplicate entry in the concurrent testing

---

wren-base/src/test/resources/tpch_mdl.json
wren-tests/src/test/java/io/wren/testing/TestMDLResource.java
wren-tests/src/test/java/io/wren/testing/TestMetadataQuery.java
wren-tests/src/test/java/io/wren/testing/bigquery/AbstractCacheTest.java
wren-tests/src/test/java/io/wren/testing/bigquery/AbstractWireProtocolTestWithBigQuery.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestBigQueryCache.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestBigQueryCacheService.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestBigQuerySqlConverter.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestCache.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestCacheTaskManager.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestDuckdbRetryCacheTask.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestReloadCache.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestResultSetMetadata.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolTypeWithBigQuery.java
wren-tests/src/test/resources/bigquery/TestResultSetMetadata.json
wren-tests/src/test/resources/bigquery/TestWireProtocolWithBigquery.json
wren-tests/src/test/resources/cache/cache_bigquery_mdl.json
wren-tests/src/test/resources/cache/cache_frequently_mdl.json
wren-tests/src/test/resources/cache/cache_mdl.json
wren-tests/src/test/resources/cache/cache_reload_1_mdl.json
wren-tests/src/test/resources/cache/cache_reload_2_mdl.json
wren-tests/src/test/resources/cache/cache_reload_3_mdl.json
wren-tests/src/test/resources/tpch_mdl.json

We change the BigQuery project ID to `wrenai`.

Modify catalog to wrenai

---

wren-main/src/main/java/io/wren/main/PreviewService.java
wren-main/src/main/java/io/wren/main/WrenManager.java
wren-tests/src/test/java/io/wren/testing/TestMDLResource.java

- Use dynamic query config in preview, dry-run and dry-plan API
- Refactor TestMDLResource

Support dynamic query mode in preview api

---

wren-base/src/main/java/io/wren/base/client/jdbc/JdbcRecordIterator.java
wren-cache/src/main/java/io/wren/cache/DuckdbRecordIterator.java
wren-main/src/main/java/io/wren/connector/postgres/PostgresRecordIterator.java
wren-main/src/main/java/io/wren/main/connector/snowflake/SnowflakeRecordIterator.java
wren-tests/src/test/java/io/wren/testing/AbstractWireProtocolTypeTest.java
wren-tests/src/test/java/io/wren/testing/bigquery/TestWireProtocolTypeWithBigQuery.java
wren-tests/src/test/java/io/wren/testing/duckdb/TestWireProtocolTypeWithDuckDB.java
wren-tests/src/test/java/io/wren/testing/snowflake/TestWireProtocolTypeWithSnowflake.java

Enhance the null result for each connector. I haven't tested the Snowflake connector. Just add some handling and test case.

Enhance null value handling

---

wren-base/src/main/java/io/wren/base/dto/Column.java
wren-base/src/main/java/io/wren/base/sqlrewrite/MetricSqlRender.java
wren-base/src/test/java/io/wren/base/sqlrewrite/TestMetric.java
wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDB.java
wren-tests/src/test/resources/duckdb/mdl.json

Fix the expression of metric dimension generating

---

wren-base/src/main/java/io/wren/base/WrenMDL.java
wren-base/src/main/java/io/wren/base/sqlrewrite/WrenSqlRewrite.java
wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
wren-base/src/test/java/io/wren/base/sqlrewrite/AbstractTestModel.java
wren-base/src/test/java/io/wren/base/sqlrewrite/TestMetric.java

close #526 
Also enhance the analysis for column usage:
- window
- aliased relation
- group by
- order by

Enhance the used columns analyze and required datasets for dynamic query mode

---

docker/Dockerfile
docker/entrypoint.sh

Add two env to set the heap size of JVM.
- MAX_HEAP_SIZE
- INI_HEAP_SIZE

Add heap_size setting env for engine image

---

.github/workflows/build.yml
.github/workflows/integration-tests.yml

close #578 
Let the v1-engine workflow only be triggered by labeled.

Modified the behavior for v1-engine CI workflow

---

wren-modeling-rs/src/logical_plan/context_provider.rs
wren-modeling-rs/src/logical_plan/rule.rs
wren-modeling-rs/src/logical_plan/utils.rs
wren-modeling-rs/src/mdl/lineage.rs
wren-modeling-rs/src/mdl/mod.rs
wren-modeling-rs/src/mdl/utils.rs

- Add more test case
- Test to link more relationship in one field

Introduce the TO_ONE relationship used by the calculated field

---

pom.xml

Upgrade DuckDB to v1.0.0. See more detail in https://github.com/duckdb/duckdb/releases/tag/v1.0.0

Upgrade DuckDB to v1.0.0

---

ibis-server/Dockerfile

Follow #625, we miss the odbc driver in the docker.

Add FreeTDS driver in Dockerfile

---

ibis-server/app/model/metadata/factory.py
ibis-server/app/model/metadata/mssql.py
ibis-server/tests/routers/ibis/test_mssql.py

implement mssql metadata apis
```json
{
"host": "localhost",
"port": "1226",
"user": "test",
"database": "test",
"password": "test"
}
}
```
- name: unique table name (might contain schema name, depends on are you listing table across schema or not )
- columns
- name: column name in the datasource
- type: column data type
- notNull: boolean, nullable or not
- description: column description(comment) if any
- properties: column properties if any
- description: table description if any
- properties
- schema: schema name to build tableReference
- catalog: catalog name to build tableReference
- table: table name to build tableReference
- primaryKey: the column name which is bind with primary constraint
```json
[
{
"name": "dbo.REGION",
"columns": [
{
"name": "R_COMMENT", …
```

implement mssql metadata apis

---

wren-base/src/main/java/io/wren/base/config/BigQueryConfig.java
wren-base/src/main/java/io/wren/base/config/DuckdbS3StyleStorageConfig.java
wren-base/src/main/java/io/wren/base/config/PostgresConfig.java
wren-base/src/main/java/io/wren/base/config/PostgresWireProtocolConfig.java
wren-base/src/main/java/io/wren/base/config/SQLGlotConfig.java
wren-base/src/main/java/io/wren/base/config/SnowflakeConfig.java
wren-base/src/main/java/io/wren/base/config/WrenConfig.java
wren-server/src/main/java/io/wren/server/module/MainModule.java
wren-tests/src/test/java/io/wren/testing/TestBackwardSupportConfig.java

Add legacy config for backward support

---

ibis-server/tests/routers/test_analysis.py

Follow #654. It misses the Python test.

Fix test case

---

ibis-server/app/config.py
ibis-server/app/logger.py
ibis-server/app/mdl/analyzer.py
ibis-server/app/mdl/rewriter.py
ibis-server/app/model/__init__.py
ibis-server/app/model/connector.py
ibis-server/app/model/metadata/dto.py
ibis-server/app/model/validator.py
ibis-server/app/util.py
ibis-server/pyproject.toml

Refer to [fastapi](https://github.com/tiangolo/fastapi/blob/master/pyproject.toml) and [ibis](https://github.com/ibis-project/ibis/blob/main/pyproject.toml).

Adjust Ruff lint

---

wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/Field.java
wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDBTableFunction.java

Support Struct and Array Syntax

---

wren-base/src/main/java/io/wren/base/client/duckdb/DuckDBConfig.java
wren-base/src/main/java/io/wren/base/client/duckdb/DuckdbClient.java
wren-base/src/main/java/io/wren/base/config/ConfigManager.java
wren-main/src/main/java/io/wren/main/PreviewService.java
wren-tests/src/test/java/io/wren/testing/TestConfigResource.java

- Increased timeout: Adjusted the timeout settings to ensure longer-running queries have sufficient time to complete without interruption.
- Removed MaxConcurrentMetadataQueries: Simplified the configuration by removing the MaxConcurrentMetadataQueries parameter. Now, the MaximumPoolSize is directly set to match the MaxConcurrentTasks, ensuring a more streamlined and efficient resource allocation.
- Added Executors for PreviewService: Introduced Executors for the PreviewService to handle concurrent tasks more effectively. This change allows each request to have a dedicated executor, improving performance and reliability during peak loads.
These enhancements aim to improve the overall performance and reliability of the system by optimizing resource management and ensuring more efficient …

Enhance DuckDB

---

ibis-server/app/model/data_source.py

Follow https://github.com/Canner/wren-engine/pull/672

Fix missing field for Trino

---

wren-modeling-py/src/lib.rs
wren-modeling-py/tests/test_modeling_core.py
wren-modeling-rs/core/src/mdl/builder.rs
wren-modeling-rs/core/src/mdl/manifest.rs
wren-modeling-rs/core/src/mdl/utils.rs
wren-modeling-rs/core/tests/data/mdl.json

Fix the format of TableReference

---

ibis-server/poetry.lock
ibis-server/pyproject.toml
ibis-server/tests/routers/v2/connector/test_clickhouse.py
ibis-server/tests/routers/v2/connector/test_postgres.py

Upgrade the Ibis version to `9.2.0` and add some tests.

feat(ibis): upgrade ibis version to 9.2.0

---

.github/dependabot.yml

Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

chore(dependabot): add `dependabot.yml` for multi module

---

.github/dependabot.yml

Group dependencies by module and separate two python module

chore(dependabot): group dependencies

---

ibis-server/app/main.py
ibis-server/app/mdl/rewriter.py
ibis-server/app/routers/v2/connector.py
ibis-server/app/routers/v3/__init__.py
ibis-server/app/routers/v3/connector.py
ibis-server/pyproject.toml
ibis-server/tests/routers/v3/connector/test_postgres.py

- V3 APIs only include `query`, `dry-run`, `dry-plan` and `validate` API
- All of the API endpoints are the same as `v2` except the prefix is `v3`.
- The `validate` API has some issues that need to be fixed. Disable the test first.
```
```
- Only test Postgres currently.

Provide the V3 API of Ibis server for the wren-core rust beta version

---

wren-modeling-py/Cargo.lock
wren-modeling-rs/sqllogictest/Cargo.toml

Fix https://cwe.mitre.org/data/definitions/532.html

Upgrade `object_store` to 0.10.2

---

ibis-server/tests/routers/v3/connector/test_postgres.py
wren-modeling-rs/core/src/logical_plan/analyze/plan.rs
wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
wren-modeling-rs/core/src/mdl/context.rs
wren-modeling-rs/core/src/mdl/mod.rs
wren-modeling-rs/sqllogictest/src/test_context.rs
wren-modeling-rs/sqllogictest/test_sql_files/model.slt
wren-modeling-rs/sqllogictest/test_sql_files/view.slt

Close #680 
- https://github.com/Canner/wren-engine/issues/728

Refactor the model planner and fix view planning

---

wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
wren-modeling-rs/core/src/mdl/mod.rs
wren-modeling-rs/sqllogictest/src/engine/runner.rs
wren-modeling-rs/sqllogictest/src/test_context.rs
wren-modeling-rs/sqllogictest/test_sql_files/view.slt

fix(core): fix query a view contain the alias expressions

---

.github/workflows/pull-request-title-validator.yaml

Example 
```
feat(client): add component
│    │        └─────── message
│    └──────────────── scope
└───────────────────── type
```
Action homepage: https://github.com/kontrolplane/pull-request-title-validator

ci(pr-title-validator): add action to validate pr title follow conventional commits

---

wren-modeling-rs/core/src/mdl/builder.rs
wren-modeling-rs/core/src/mdl/manifest.rs
wren-modeling-rs/core/tests/data/mdl.json

fix(core): the `properties` should be a json object in the MDL file

---

.github/workflows/ibis-ci.yml
ibis-server/Dockerfile
ibis-server/app/model/__init__.py
ibis-server/app/model/data_source.py
ibis-server/docs/development.md
ibis-server/tests/routers/v2/connector/test_mssql.py

Revert "fix(mssql): use msodbcsql instead of tdsodbc (#742)"
This reverts commit 50401d1455faf4a992b6f2753a324a3be746bbf9.

fix: keep using tdsodbc until web could support

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add a common template for bug reporting and feature request.

chore: add bug_report and feature_request template

---

wren-modeling-py/Cargo.lock
wren-modeling-rs/core/Cargo.toml
wren-modeling-rs/core/src/logical_plan/analyze/relation_chain.rs
wren-modeling-rs/core/src/logical_plan/analyze/rule.rs
wren-modeling-rs/core/src/mdl/lineage.rs
wren-modeling-rs/core/src/mdl/mod.rs
wren-modeling-rs/core/src/mdl/utils.rs
wren-modeling-rs/sqllogictest/test_files/view.slt

Fix the known issue about view of #766

fix(core): fix the calculation column of the view with case sensitive name

---

wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/ExpressionAnalyzer.java
wren-base/src/main/java/io/wren/base/sqlrewrite/analyzer/StatementAnalyzer.java
wren-tests/src/test/java/io/wren/testing/duckdb/TestWrenWithDuckDB.java

- Close #792 
- Fix the count aggregation
- Fix the subquery anlaysis
- enhance the tests for the syntax `count`

fix(core): fix the aggregation count for CTEs and the scope analysis for the subquery

---

ibis-server/app/model/metadata/bigquery.py
ibis-server/app/model/metadata/dto.py

- Provide record type columns of BigQuery in metadata/tables API

feat(ibis): Support BigQuery record type columns

---

README.md

chore(doc): update README.md

---

.github/labeler.yml

Continues #832
I messed up and made a typo.

ci(labeler): fix rule

---

.github/workflows/build-dev-image.yml
.github/workflows/build-image.yml
.github/workflows/stable-release.yml

Change the ordering to get the version number.

chore(ci): fix the building flow of java engine image

---

ibis-server/docs/how-to-add-data-source.md

docs: update how-to-add-data-source.md

---

.github/dependabot.yml
.github/workflows/pull-request-title-validator.yaml

- Adjust PR title from dependabot to `deps(ibis)` or `deps(core)`
- Expand PR title validator type scope

ci(dependabot): adjust prefix

---

.github/workflows/build-dev-image.yml

Follow https://github.com/Canner/wren-engine/pull/884

ci: fix by removing non-existent job

---

ibis-server/tests/routers/v2/connector/test_mssql.py

Pull out test case to avoid affect other cases

test(mssql): pull out test case about special characters

---

wren-core/core/src/mdl/context.rs
wren-core/core/src/mdl/mod.rs

feat(core): disable `EliminateNestedUnion` 

---

ibis-server/tests/routers/v3/connector/postgres/conftest.py
ibis-server/tests/routers/v3/connector/postgres/test_query.py
ibis-server/tools/mdl_validation.py
wren-core/core/src/logical_plan/analyze/model_generation.rs
wren-core/core/src/logical_plan/analyze/plan.rs
wren-core/core/src/logical_plan/analyze/relation_chain.rs
wren-core/core/src/logical_plan/utils.rs
wren-core/core/src/mdl/mod.rs
wren-core/wren-example/examples/to-many-calculation.rs

feat(core): avoid to generate unnamed subquery when planning calculated fields

---

wren-main/src/main/java/io/wren/main/PreviewService.java

chore(java): make manifest complex to warm more class up

---

wren-core/core/src/mdl/builder.rs
wren-core/core/src/mdl/manifest.rs
wren-core/core/tests/data/mdl.json

feat(core): add `dataSource` field to MDL

---

.github/workflows/ibis-ci.yml
.github/workflows/stable-release.yml
ibis-server/Dockerfile
ibis-server/README.md
ibis-server/docs/development.md
ibis-server/justfile
wren-core-py/justfile

- Merge `update-core` into `install-core`
- Combo `install` with `install-core`
- Make the release flag via env var.

chore: merge just commands

---

wren-core/core/src/logical_plan/analyze/model_anlayze.rs
wren-core/core/src/mdl/mod.rs
wren-core/sqllogictest/test_files/model.slt

feat(core): support querying window function

---

.github/workflows/build-image.yml
.github/workflows/stable-release.yml
ibis-server/Dockerfile
ibis-server/justfile

I missed adding the context for image building flow.

fix(core): add missing context for image building

---

ibis-server/tests/conftest.py
wren-core-py/Cargo.lock
wren-core-py/tests/test_modeling_core.py
wren-core/Cargo.toml
wren-core/core/src/logical_plan/analyze/model_anlayze.rs
wren-core/core/src/logical_plan/analyze/plan.rs
wren-core/core/src/logical_plan/utils.rs
wren-core/core/src/mdl/context.rs
wren-core/core/src/mdl/dialect/utils.rs
wren-core/core/src/mdl/lineage.rs
wren-core/core/src/mdl/mod.rs
wren-core/sqllogictest/test_files/tpch/q22.slt.part

revert: upgrade DataFusion to 46.0.0

---

ibis-server/tests/routers/v2/connector/test_gcs_file.py
ibis-server/tests/routers/v2/connector/test_local_file.py
ibis-server/tests/routers/v2/connector/test_minio_file.py
ibis-server/tests/routers/v2/connector/test_s3_file.py
wren-core-base/manifest-macro/src/lib.rs
wren-core-base/src/mdl/manifest.rs

MCP local file connector needs a datasource field.

chore(ibis): Cherry-pick the commit related to file connector datasource serde

---

wren-core-py/Cargo.lock

- close https://github.com/Canner/wren-engine/issues/1201
- datafusion dependency point to https://github.com/Canner/datafusion/pull/2

fix(core): disable eliminating sort in subquery
